# Authoritative Database of Verified Government Schemes - Part 1 (Schemes 26 to 50)
# Sourced exclusively from official Government of India Gazettes, Portals, and Ministry Guidelines

SCHEMES_PART1 = [
    {
        "scheme_id": "SVEP-MORD-26",
        "official_scheme_name": "Start-up Village Entrepreneurship Programme (SVEP)",
        "short_description": "Sub-scheme under DAY-NRLM to help rural poor women and SHG members set up local non-farm enterprises with financial assistance and business support.",
        "ministry": "Ministry of Rural Development (MoRD)",
        "department": "Rural Livelihoods Division",
        "target_beneficiaries": "Rural poor women, SHG members, and rural entrepreneurs setting up small manufacturing, service, and retail enterprises.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": 150000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Rural women entrepreneurs, SHG members, Artisans, Small shopkeepers",
        "business_type": "Manufacturing, Service, Trading / Retail",
        "project_type": "Rural village enterprises, local grocery, tailoring, dairy, small processing",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹2,00,000 through Community Enterprise Fund (CEF).",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 200000.0,
        "financial_assistance": "Soft loans from Community Enterprise Fund (CEF) managed by Block Resource Centres (BRC).",
        "subsidy_details": "Interest subvention and business support via Community Resource Persons - Enterprise Promotion (CRP-EP).",
        "subsidy_percentage": 5.0,
        "max_subsidy_amount": 10000.0,
        "interest_rate": "Soft interest rate between 4% to 7% p.a.",
        "margin_money": "5% to 10% promoter contribution.",
        "repayment_period": "Up to 3 to 5 years",
        "moratorium": "3 months",
        "collateral_requirement": "No collateral or third-party guarantee required.",
        "project_cost_limit": 250000.0,
        "benefits": "Dedicated CRP-EP business handholding, bookkeeping training, soft capital loans, local market linkage.",
        "required_documents": "Aadhaar Card, SHG Membership Certificate, Bank Account Passbook, Village Organization resolution, Simple Business Plan.",
        "application_mode": "Offline through Block Resource Centre (BRC) / Gram Panchayat",
        "application_steps": "1. Approach local Block Resource Centre (BRC) or Village Organization (VO). 2. Request assistance from Community Resource Person - Enterprise Promotion (CRP-EP). 3. Prepare simple viability business plan. 4. BRC approves proposal and sanctions Community Enterprise Fund loan. 5. Funds disbursed directly to applicant bank account.",
        "official_application_portal": "https://nrlm.gov.in/",
        "application_portal_name": "DAY-NRLM / SVEP Portal",
        "application_tracking_available": True,
        "tracking_url": "https://nrlm.gov.in/",
        "tracking_instructions": "Track proposal status at the Block Resource Centre (BRC) or via Village Organization (VO) committee meeting records.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Block Resource Centres (BRC), State Rural Livelihoods Missions (SRLM), Public Sector Banks",
        "official_helpline": "011-23381611",
        "official_email": "svep.nrlm@gov.in",
        "official_source_url": "https://nrlm.gov.in/",
        "official_guideline_url": "https://nrlm.gov.in/outer/view/guidelines.jsp",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "AGY-MORD-27",
        "official_scheme_name": "Aajeevika Grameen Express Yojana (AGY)",
        "short_description": "Provides interest-free loans up to ₹6.5 Lakh to women SHG members to operate public passenger and cargo transport vehicles in remote rural areas.",
        "ministry": "Ministry of Rural Development (MoRD)",
        "department": "Rural Livelihoods Division",
        "target_beneficiaries": "Rural women SHG members operating under Deendayal Antyodaya Yojana - NRLM.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "21 to 55 years",
        "minimum_age": 21,
        "maximum_age": 55,
        "income_limit": 200000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Rural women drivers, SHG members, Rural transport operators",
        "business_type": "Service",
        "project_type": "Rural passenger transport (e-rickshaw, auto, 4-wheeler mini-bus) connecting backward villages to markets",
        "education_requirements": "Valid driving license or undertaking to acquire commercial driving license.",
        "loan_amount": "Interest-free loan up to ₹6,50,000 provided by Community Based Organisations (CBO).",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 650000.0,
        "financial_assistance": "100% interest-free loan through Community Investment Fund (CIF) to purchase commercial vehicle.",
        "subsidy_details": "0% interest loan (100% interest subvention borne by NRLM / CBO).",
        "subsidy_percentage": 0.0,
        "max_subsidy_amount": 0.0,
        "interest_rate": "0% (Interest-Free)",
        "margin_money": "No margin money required if vehicle is within CIF sanction limit.",
        "repayment_period": "Up to 6 years (maximum 72 months)",
        "moratorium": "1 month",
        "collateral_requirement": "Hypothecation of the vehicle to the Community Based Organisation (CBO).",
        "project_cost_limit": 650000.0,
        "benefits": "Zero interest financing, guaranteed transport route allotted by Regional Transport Authority, vehicle ownership by rural woman.",
        "required_documents": "Aadhaar Card, Valid Driving License, SHG Membership Certificate, Cluster Level Federation (CLF) recommendation, Proof of Residence.",
        "application_mode": "Offline via Block Mission Management Unit (BMMU) / CLF",
        "application_steps": "1. Express interest at the Gram Panchayat / Cluster Level Federation (CLF). 2. Route survey conducted by SRLM transport coordinator. 3. Application submitted to CLF executive committee. 4. CIF fund sanctioned and vehicle purchased directly from authorised dealer. 5. Permit and fitness clearance facilitated by BMMU.",
        "official_application_portal": "https://aajeevika.gov.in/",
        "application_portal_name": "MoRD Aajeevika Portal",
        "application_tracking_available": True,
        "tracking_url": "https://aajeevika.gov.in/",
        "tracking_instructions": "Check application status with Block Project Manager (BPM) at Block Mission Management Unit.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Cluster Level Federations (CLF), State Rural Livelihood Missions (SRLM), Regional Transport Offices",
        "official_helpline": "011-23386173",
        "official_email": "agey.mord@gov.in",
        "official_source_url": "https://aajeevika.gov.in/",
        "official_guideline_url": "https://aajeevika.gov.in/sites/default/files/guidelines/AGEY_Guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "MKSP-MORD-28",
        "official_scheme_name": "Mahila Kisan Sashaktikaran Pariyojana (MKSP)",
        "short_description": "Promotes agro-ecological practices and micro-livelihoods for rural women farmers through dedicated community training, seed funds, and collective farming inputs.",
        "ministry": "Ministry of Rural Development (MoRD)",
        "department": "Department of Rural Development",
        "target_beneficiaries": "Small and marginal women farmers, tribal farmwomen, and landless agricultural labourers.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": 150000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Women Farmers, Agricultural Labourers, Non-Timber Forest Produce (NTFP) Gatherers",
        "business_type": "Agri-Allied",
        "project_type": "Organic farming, kitchen gardens, bio-inputs production, NTFP collection and aggregation",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹1,50,000 input assistance and revolving fund via SHG.",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 150000.0,
        "financial_assistance": "Direct project grant to Community Resource Persons (Krishi Sakhi) and input subsidy to women farmer collectives.",
        "subsidy_details": "Grant assistance up to 60% (75% for special states) for community agricultural infrastructure and input subsidies.",
        "subsidy_percentage": 60.0,
        "max_subsidy_amount": 90000.0,
        "interest_rate": "Zero interest / Soft interest under SHG bank linkage.",
        "margin_money": "No margin money required for individual beneficiaries.",
        "repayment_period": "2 to 3 years for revolving funds",
        "moratorium": "6 months",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 200000.0,
        "benefits": "Free training by Krishi Sakhis, biological pest control support, indigenous seed banks, direct market linkage through producer groups.",
        "required_documents": "Aadhaar Card, SHG Passbook, Land possession certificate / lease agreement or MGNREGA Job Card.",
        "application_mode": "Through Gram Panchayat / Village Krishi Sakhi",
        "application_steps": "1. Register with local Village Organization (VO) Krishi Sakhi. 2. Attend farmer field school on sustainable agriculture. 3. Join Mahila Kisan Producer Group. 4. Receive input package and revolving fund. 5. Aggregate produce for collective marketing.",
        "official_application_portal": "https://mksp.gov.in/",
        "application_portal_name": "MKSP National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://mksp.gov.in/",
        "tracking_instructions": "Inquire with Block Technology Manager (BTM) under ATMA or SRLM Krishi Sakhi.",
        "channel_partner_requirement": True,
        "channel_partner_types": "State Rural Livelihoods Missions, ATMA (Agriculture Technology Management Agency), Krishi Vigyan Kendras (KVK)",
        "official_helpline": "011-23382417",
        "official_email": "mksp-mord@gov.in",
        "official_source_url": "https://mksp.gov.in/",
        "official_guideline_url": "https://mksp.gov.in/guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "KCC-ALLIED-29",
        "official_scheme_name": "Kisan Credit Card (KCC) for Animal Husbandry & Fisheries",
        "short_description": "Extends short-term working capital credit up to ₹2 Lakh at a subsidized interest rate of 4% p.a. for livestock, dairy, sheep/goat, and fisheries rearing.",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying (MoFAHD)",
        "department": "Department of Animal Husbandry and Dairying",
        "target_beneficiaries": "Small and marginal farmers, dairy farmers, poultry farmers, goat/sheep rearers, and fishers.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 70 years",
        "minimum_age": 18,
        "maximum_age": 70,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Dairy Farmers, Goat Keepers, Pig Farmers, Poultry Operators, Fish Farmers",
        "business_type": "Agri-Allied",
        "project_type": "Working capital for feed, veterinary medicines, water and electricity for livestock/fishery",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹2,00,000 working capital loan (up to ₹3 Lakh if combined with crop loan).",
        "min_loan_amount": 25000.0,
        "max_loan_amount": 200000.0,
        "financial_assistance": "Revolving cash credit limit on Kisan Credit Card.",
        "subsidy_details": "2% Interest Subvention (IS) and additional 3% Prompt Repayment Incentive (PRI), effectively reducing interest to 4% p.a.",
        "subsidy_percentage": 5.0,
        "max_subsidy_amount": 10000.0,
        "interest_rate": "Effective 4% p.a. (with Prompt Repayment Incentive)",
        "margin_money": "No margin money required for loans up to ₹1.60 Lakh.",
        "repayment_period": "1 year revolving credit (renewable every 12 months)",
        "moratorium": "Not applicable (Revolving cash credit)",
        "collateral_requirement": "No collateral required for loans up to ₹1.60 Lakh (extendable to ₹2 Lakh without collateral under RBI guidelines).",
        "project_cost_limit": 200000.0,
        "benefits": "Extremely low 4% effective interest rate, instant liquidity via ATM-enabled RuPay KCC card, hassle-free renewal.",
        "required_documents": "Aadhaar Card, PAN Card, Livestock / Animal possession proof or lease agreement, Bank Account details.",
        "application_mode": "Online on JanSamarth or Offline at any Bank branch",
        "application_steps": "1. Download simple 1-page KCC application from dahd.nic.in or apply on jansamarth.in. 2. Submit to local public sector bank, RRB, or Cooperative Bank. 3. Bank assesses animal units. 4. Card issued within 14 days of application.",
        "official_application_portal": "https://www.jansamarth.in/",
        "application_portal_name": "JanSamarth / Department of Animal Husbandry Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.jansamarth.in/",
        "tracking_instructions": "Log on to jansamarth.in using mobile number to check lead generation and branch sanction status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Public Sector Commercial Banks, Regional Rural Banks (RRBs), District Cooperative Banks",
        "official_helpline": "1800-180-1551",
        "official_email": "dahd@nic.in",
        "official_source_url": "https://dahd.nic.in/",
        "official_guideline_url": "https://dahd.nic.in/schemes/programmes/kisan-credit-card",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "AIF-AGRI-30",
        "official_scheme_name": "Agriculture Infrastructure Fund (AIF)",
        "short_description": "Pan-India medium to long term debt financing facility providing 3% interest subvention and CGTMSE credit guarantee for post-harvest management projects.",
        "ministry": "Ministry of Agriculture and Farmers Welfare (MoA&FW)",
        "department": "Department of Agriculture and Farmers Welfare",
        "target_beneficiaries": "Primary Agricultural Credit Societies (PACS), FPOs, SHGs, Joint Liability Groups (JLGs), Agri-entrepreneurs, Start-ups.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Agri-entrepreneurs, Farmers, FPO Members, Cold Storage Owners, Food Processors",
        "business_type": "Agri-Allied, Service, Manufacturing",
        "project_type": "Post-harvest infrastructure: warehouses, cold rooms, sorting/grading units, drying yards, primary processing",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Term loans up to ₹2 Crore per project eligible for interest subvention.",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 20000000.0,
        "financial_assistance": "Bank term loans with 3% per annum interest subvention for a maximum of 7 years.",
        "subsidy_details": "3% per annum interest subvention and CGTMSE fee coverage up to ₹2 Crore funded entirely by Central Government.",
        "subsidy_percentage": 3.0,
        "max_subsidy_amount": 600000.0,
        "interest_rate": "Bank lending rate minus 3% interest subvention (effective rate ~6.5% - 7.5% p.a.).",
        "margin_money": "Minimum 10% to 20% promoter contribution.",
        "repayment_period": "Up to 10 years",
        "moratorium": "6 months to 2 years depending on gestation period.",
        "collateral_requirement": "Covered under CGTMSE guarantee scheme for loans up to ₹2 Crore.",
        "project_cost_limit": 20000000.0,
        "benefits": "3% lower interest for 7 years, CGTMSE fee paid by GoI, rapid single-window online sanction.",
        "required_documents": "Detailed Project Report (DPR), Land revenue records / lease deed, PAN Card, Aadhaar Card, Bank statement of last 6 months.",
        "application_mode": "Online on AIF Portal",
        "application_steps": "1. Visit agriinfra.dac.gov.in. 2. Register as 'Beneficiary'. 3. Fill basic details, project proposal and DPR. 4. Select preferred participating bank. 5. MoA&FW evaluates project within 7 days. 6. Bank approves term loan online.",
        "official_application_portal": "https://agriinfra.dac.gov.in/",
        "application_portal_name": "Agri Infrastructure National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://agriinfra.dac.gov.in/",
        "tracking_instructions": "Log on to agriinfra.dac.gov.in with registered user credentials. Application progress shows Ministry approval, Bank sanction, and CGTMSE guarantee status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "All Scheduled Commercial Banks, NABARD, Cooperative Banks, Regional Rural Banks",
        "official_helpline": "011-23381012 / 011-23382012",
        "official_email": "aif-dac@gov.in",
        "official_source_url": "https://agriinfra.dac.gov.in/",
        "official_guideline_url": "https://agriinfra.dac.gov.in/Home/Guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "SMAM-AGRI-31",
        "official_scheme_name": "Sub-Mission on Agricultural Mechanization (SMAM) - Custom Hiring Centres",
        "short_description": "Offers 40% to 50% capital subsidy (up to ₹10 Lakh) to rural youth and entrepreneurs to establish Custom Hiring Centres (CHC) for farm machinery.",
        "ministry": "Ministry of Agriculture and Farmers Welfare (MoA&FW)",
        "department": "Department of Agriculture and Farmers Welfare",
        "target_beneficiaries": "Rural youth, Farmers, Farmer Producer Organisations (FPOs), Cooperative Societies, SHGs.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 55 years",
        "minimum_age": 18,
        "maximum_age": 55,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Rural Youth, Agri-Entrepreneurs, Tractor Owners, Custom Hiring Operators",
        "business_type": "Service, Agri-Allied",
        "project_type": "Setting up farm machinery rental centers (tractors, harvesters, laser levelers, drone sprayers)",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Project cost up to ₹10 Lakh for Individual CHC (up to ₹25 Lakh for FPOs).",
        "min_loan_amount": 200000.0,
        "max_loan_amount": 2500000.0,
        "financial_assistance": "Direct Benefit Transfer (DBT) capital subsidy credited to beneficiary bank account.",
        "subsidy_details": "40% subsidy for General category (max ₹4 Lakh); 50% subsidy for SC/ST/Women/Small & Marginal farmers (max ₹5 Lakh) on project up to ₹10 Lakh.",
        "subsidy_percentage": 50.0,
        "max_subsidy_amount": 500000.0,
        "interest_rate": "Commercial bank lending rate on the loan portion.",
        "margin_money": "10% to 20% promoter contribution.",
        "repayment_period": "5 to 7 years",
        "moratorium": "6 months",
        "collateral_requirement": "Hypothecation of agricultural machinery purchased.",
        "project_cost_limit": 1000000.0,
        "benefits": "Substantial capital subsidy, high local rental income from farm machinery, boosts farm efficiency.",
        "required_documents": "Aadhaar Card, Land ownership/lease documents, Driving license/tractor operator certificate, Bank passbook, Quotation from authorized machinery dealers.",
        "application_mode": "Online on Agromachinery Portal",
        "application_steps": "1. Visit agrimachinery.nic.in. 2. Select 'Registration for CHC'. 3. Choose equipment package from approved list. 4. Upload quotations and land records. 5. District Agriculture Officer conducts online verification. 6. Subsidy released directly to bank account via DBT upon machinery delivery.",
        "official_application_portal": "https://agrimachinery.nic.in/",
        "application_portal_name": "Agri-Machinery DBT Portal",
        "application_tracking_available": True,
        "tracking_url": "https://agrimachinery.nic.in/",
        "tracking_instructions": "Enter Application Reference Number on the Agromachinery DBT Portal to track district approval and fund disbursement.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Agriculture Offices, Commercial Banks, State Agro Industries Corporations",
        "official_helpline": "011-23382937",
        "official_email": "smam-agri@gov.in",
        "official_source_url": "https://agrimachinery.nic.in/",
        "official_guideline_url": "https://agrimachinery.nic.in/Guidelines/SMAM_Guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PKVY-AGRI-32",
        "official_scheme_name": "Paramparagat Krishi Vikas Yojana (PKVY)",
        "short_description": "Promotes organic farming through cluster approach, providing ₹50,000 per hectare financial assistance over 3 years for inputs, certification, and packaging.",
        "ministry": "Ministry of Agriculture and Farmers Welfare (MoA&FW)",
        "department": "National Project on Organic Farming (NPOF)",
        "target_beneficiaries": "Small and marginal farmers, rural youth, tribal farmers, and organic farming clusters.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 70 years",
        "minimum_age": 18,
        "maximum_age": 70,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Organic Farmers, Small & Marginal Farmers, Agri-input Producers",
        "business_type": "Agri-Allied, Manufacturing",
        "project_type": "Organic crop cultivation, PGS certification, vermicompost production, organic value-addition and packing",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Financial assistance of ₹50,000 per hectare (up to 2 hectares per farmer in a 20 ha / 50 acre cluster).",
        "min_loan_amount": 20000.0,
        "max_loan_amount": 100000.0,
        "financial_assistance": "Direct Benefit Transfer (DBT) of ₹31,000/ha for organic inputs + ₹8,800/ha for value addition, marketing, and packing.",
        "subsidy_details": "100% grant assistance of ₹50,000/ha over a 3-year cycle.",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 100000.0,
        "interest_rate": "Grant / Nil (100% Government Assistance)",
        "margin_money": "No margin money required.",
        "repayment_period": "Grant (No repayment)",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 100000.0,
        "benefits": "Free PGS-India organic certification, 100% grant for inputs and branding, premium pricing for organic produce at Jaivik Kheti portal.",
        "required_documents": "Aadhaar Card, Land ownership record (Khasra/Khatauni), Bank Passbook, Cluster membership consent.",
        "application_mode": "Offline via Regional Council / District Agriculture Office or Online via Jaivik Kheti",
        "application_steps": "1. Form or join a group of 20-50 farmers (minimum 20 hectares total). 2. Register cluster on jaivikkheti.in or with District Agriculture Officer. 3. Participate in PGS-India peer inspection. 4. Receive direct DBT installments for seeds, bio-fertilisers, and harvesting. 5. Market produce on Jaivik Kheti portal.",
        "official_application_portal": "https://www.jaivikkheti.in/",
        "application_portal_name": "Jaivik Kheti National Organic Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.jaivikkheti.in/",
        "tracking_instructions": "Log on to jaivikkheti.in with Farmer ID or mobile number to track cluster verification and DBT releases.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Regional Councils (RC) under PGS-India, District Agriculture Offices, Krishi Vigyan Kendras",
        "official_helpline": "011-23381012",
        "official_email": "pkvy-agri@nic.in",
        "official_source_url": "https://pgsindia-ncof.gov.in/",
        "official_guideline_url": "https://daccfw.gov.in/sites/default/files/PKVY_guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PM-FME-MICRO-33",
        "official_scheme_name": "PM Formalisation of Micro food processing Enterprises (PM-FME)",
        "short_description": "Provides 35% credit-linked capital subsidy up to ₹10 Lakh for individual micro food processing enterprises and ₹40,000 seed capital per SHG member.",
        "ministry": "Ministry of Food Processing Industries (MoFPI)",
        "department": "National Institute of Food Technology Entrepreneurship and Management (NIFTEM)",
        "target_beneficiaries": "Existing and aspiring micro food processing entrepreneurs, Women SHG members, FPOs, Producer Cooperatives.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Micro Food Processors, Pickle/Spice Makers, Flour Millers, Bakery Owners, SHG Members",
        "business_type": "Manufacturing",
        "project_type": "Micro food processing units under One District One Product (ODOP) or non-ODOP (grains, spices, fruits, dairy, snacks)",
        "education_requirements": "At least 8th class pass preferred for individual units.",
        "loan_amount": "Up to ₹30 Lakh project cost with 35% subsidy (maximum subsidy ₹10 Lakh).",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 3000000.0,
        "financial_assistance": "Credit-linked capital subsidy of 35% of eligible project cost credited to bank loan account.",
        "subsidy_details": "35% credit-linked capital subsidy (max ₹10,00,000). For SHG members, seed capital of ₹40,000 per member for working capital and tools.",
        "subsidy_percentage": 35.0,
        "max_subsidy_amount": 1000000.0,
        "interest_rate": "Commercial bank lending rate on MSME loans.",
        "margin_money": "Minimum 10% promoter contribution.",
        "repayment_period": "5 to 7 years",
        "moratorium": "6 to 12 months",
        "collateral_requirement": "Covered under Credit Guarantee Scheme for Micro and Small Enterprises (CGTMSE).",
        "project_cost_limit": 3000000.0,
        "benefits": "Generous 35% capital subsidy, free handholding by District Resource Persons (DRP), FSSAI registration assistance, branding support.",
        "required_documents": "Aadhaar Card, PAN Card, Detailed Project Report (DPR), Bank statement of 6 months, FSSAI registration (or undertaking), Lease/Ownership of premises.",
        "application_mode": "Online on PMFME Portal",
        "application_steps": "1. Visit pmfme.mofpi.gov.in. 2. Register as 'Beneficiary'. 3. Choose District Resource Person (DRP) for free project assistance. 4. Complete online application and upload DPR. 5. Forwarded to State Nodal Agency and Bank. 6. Bank sanctions loan and claims subsidy from MoFPI.",
        "official_application_portal": "https://pmfme.mofpi.gov.in/",
        "application_portal_name": "PMFME National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://pmfme.mofpi.gov.in/",
        "tracking_instructions": "Log on to pmfme.mofpi.gov.in with application login to track DRP scrutiny, District Level Committee review, and Bank sanction.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Resource Persons (DRP), State Nodal Agencies (SNA), Public Sector Banks",
        "official_helpline": "1800-111-107 / 011-26493227",
        "official_email": "pmfme-mofpi@gov.in",
        "official_source_url": "https://mofpi.gov.in/",
        "official_guideline_url": "https://pmfme.mofpi.gov.in/pmfme/#/Home-Page/guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMMSY-AQUA-34",
        "official_scheme_name": "Pradhan Mantri Matsya Sampada Yojana (PMMSY) - Aquaculture & Fish Farming",
        "short_description": "Flagship scheme providing 40% (General) to 60% (SC/ST/Women) subsidy for establishing freshwater fish ponds, biofloc, RAS units, and fish seed hatcheries.",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying (MoFAHD)",
        "department": "Department of Fisheries",
        "target_beneficiaries": "Fishers, Fish Farmers, Fish Workers, SC/ST fishers, Women SHGs, Fisheries Cooperatives.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Fish Farmers, Aquaculture Entrepreneurs, Traditional Fishers, SHG Members",
        "business_type": "Agri-Allied, Manufacturing",
        "project_type": "Freshwater aquaculture pond construction, Biofloc system, Recirculatory Aquaculture System (RAS), cage culture",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Project cost from ₹7 Lakh (ponds) up to ₹50 Lakh (medium RAS units).",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 5000000.0,
        "financial_assistance": "Direct back-ended capital subsidy of 40% (General) or 60% (SC/ST/Women) of unit cost.",
        "subsidy_details": "40% subsidy for General Category; 60% subsidy for SC, ST, and Women beneficiaries.",
        "subsidy_percentage": 60.0,
        "max_subsidy_amount": 3000000.0,
        "interest_rate": "Commercial bank lending rate on MSME / Agri loan.",
        "margin_money": "10% to 20% promoter contribution.",
        "repayment_period": "5 to 7 years",
        "moratorium": "6 to 12 months",
        "collateral_requirement": "Hypothecation of aquaculture assets created.",
        "project_cost_limit": 5000000.0,
        "benefits": "Highest subsidy in aquaculture (up to 60%), technical training from NFDB, disease surveillance, cold chain integration.",
        "required_documents": "Aadhaar Card, Land ownership papers or minimum 7-year registered water body lease, Detailed Project Report, Bank account details, Caste certificate (for SC/ST).",
        "application_mode": "Online on PMMSY Portal or Offline via District Fisheries Office",
        "application_steps": "1. Visit pmmsy.dof.gov.in. 2. Register as 'Applicant / Entrepreneur'. 3. Select scheme component (e.g. Biofloc / Pond Aquaculture). 4. Upload DPR and land/pond documents. 5. District Level Committee (DLC) inspects site and approves. 6. Subsidy released in installments based on project milestone verification.",
        "official_application_portal": "https://pmmsy.dof.gov.in/",
        "application_portal_name": "PMMSY National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://pmmsy.dof.gov.in/",
        "tracking_instructions": "Log on to pmmsy.dof.gov.in with Applicant User ID. View District Fisheries Officer scrutiny, State Committee sanction, and subsidy release status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Fisheries Offices (DFO), Scheduled Commercial Banks, State Fisheries Federations",
        "official_helpline": "1800-425-1660",
        "official_email": "pmmsy-dof@gov.in",
        "official_source_url": "https://pmmsy.dof.gov.in/",
        "official_guideline_url": "https://pmmsy.dof.gov.in/guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "NLM-LIVESTOCK-35",
        "official_scheme_name": "National Livestock Mission (NLM) - Entrepreneurship Development",
        "short_description": "Provides 50% capital subsidy up to ₹50 Lakh for rural entrepreneurs to set up sheep, goat, piggery, and rural poultry breeding farms and feed/fodder units.",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying (MoFAHD)",
        "department": "Department of Animal Husbandry and Dairying (DAHD)",
        "target_beneficiaries": "Rural entrepreneurs, Farmers, SHGs, FPOs, Cooperatives, SC/ST livestock owners.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Livestock Keepers, Poultry Breeders, Goat Farmers, Feed Millers",
        "business_type": "Agri-Allied, Manufacturing",
        "project_type": "Commercial sheep/goat breeding farm, rural poultry parent farm, silage/fodder manufacturing plant",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "50% capital subsidy on projects up to ₹1 Crore (max subsidy ₹50 Lakh).",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 10000000.0,
        "financial_assistance": "Direct capital back-ended subsidy of 50% of project cost credited in two equal installments via SIDBI.",
        "subsidy_details": "50% Capital Subsidy (up to ₹25 Lakh for Poultry, up to ₹50 Lakh for Sheep/Goat breeding, up to ₹30 Lakh for Piggery).",
        "subsidy_percentage": 50.0,
        "max_subsidy_amount": 5000000.0,
        "interest_rate": "Bank MSME lending rate on remaining loan amount.",
        "margin_money": "Minimum 10% to 20% promoter contribution.",
        "repayment_period": "5 to 7 years",
        "moratorium": "Up to 12 months",
        "collateral_requirement": "Hypothecation of livestock assets and farm structures.",
        "project_cost_limit": 10000000.0,
        "benefits": "Huge 50% capital subsidy, fast online portal, technical training through ICAR institutes, high rural income potential.",
        "required_documents": "Detailed Project Report (DPR), Land records / registered lease for minimum 10 years, Bank In-principle sanction letter, Caste certificate (if SC/ST), Aadhaar & PAN.",
        "application_mode": "Online on NLM Portal",
        "application_steps": "1. Visit nlm.udyamimitra.in. 2. Register as Entrepreneur. 3. Upload DPR and land documents. 4. State Implementing Agency (SIA) inspects farm site. 5. Sanction issued and 1st 50% subsidy installment released via SIDBI after bank disbursement.",
        "official_application_portal": "https://nlm.udyamimitra.in/",
        "application_portal_name": "NLM Udyamimitra Portal",
        "application_tracking_available": True,
        "tracking_url": "https://nlm.udyamimitra.in/",
        "tracking_instructions": "Log on to nlm.udyamimitra.in with application credentials to track SIA verification, Bank sanction, and SIDBI subsidy release.",
        "channel_partner_requirement": True,
        "channel_partner_types": "State Implementing Agencies (SIA), Commercial Banks, SIDBI",
        "official_helpline": "011-23381012",
        "official_email": "nlm-dahd@nic.in",
        "official_source_url": "https://dahd.nic.in/",
        "official_guideline_url": "https://dahd.nic.in/schemes/programmes/nlm",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "HONEY-KVIC-36",
        "official_scheme_name": "Honey Mission (Sweet Kranti) - KVIC",
        "short_description": "Promotes beekeeping among rural and tribal youth, providing 10 bee boxes with live bee colonies at an 80% subsidy and free technical training.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "Khadi and Village Industries Commission (KVIC)",
        "target_beneficiaries": "Rural youth, farmers, landless agricultural workers, SC/ST communities, and tribal forest-edge dwellers.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": 200000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Beekeepers, Rural Farmers, Forest Dwellers, Artisans",
        "business_type": "Agri-Allied, Manufacturing",
        "project_type": "Apiculture, raw honey extraction, beeswax processing, pollinator conservation",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Package of 10 bee colonies and toolkits worth ₹40,000 (Beneficiary pays only 20%).",
        "min_loan_amount": 8000.0,
        "max_loan_amount": 40000.0,
        "financial_assistance": "80% equipment subsidy provided directly in-kind by KVIC; 20% beneficiary contribution.",
        "subsidy_details": "80% government subsidy on cost of 10 bee-boxes, colonies, honey extractor, and protective kits.",
        "subsidy_percentage": 80.0,
        "max_subsidy_amount": 32000.0,
        "interest_rate": "Nil (In-kind equipment subsidy)",
        "margin_money": "20% (approx ₹8,000 paid by beneficiary for 10 boxes).",
        "repayment_period": "Not applicable (Grant / In-kind kit)",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 50000.0,
        "benefits": "80% subsidy, 5 days hands-on practical beekeeping training, buy-back facilitation of pure honey by KVIC.",
        "required_documents": "Aadhaar Card, Bank Passbook copy, Passport-size photo, Proof of rural residence.",
        "application_mode": "Online on KVIC Portal or Offline at State KVIC Office",
        "application_steps": "1. Apply online on kviconline.gov.in under Honey Mission. 2. District KVIC officer verifies applicant rural location. 3. Attend mandatory 5-day beekeeping training at KVIC multi-disciplinary training centre. 4. Pay 20% contribution. 5. Receive 10 live bee boxes and honey harvesting kit.",
        "official_application_portal": "https://www.kviconline.gov.in/",
        "application_portal_name": "KVIC Honey Mission Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.kviconline.gov.in/",
        "tracking_instructions": "Check application status with the State Director of KVIC or via online application acknowledgment receipt.",
        "channel_partner_requirement": True,
        "channel_partner_types": "KVIC State Offices, District Industries Centres (DIC), Krishi Vigyan Kendras",
        "official_helpline": "022-26711002",
        "official_email": "honeymission.kvic@gov.in",
        "official_source_url": "https://www.kvic.gov.in/",
        "official_guideline_url": "https://www.kvic.gov.in/honey-mission-guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "KUMBHAR-KVIC-37",
        "official_scheme_name": "Kumbhar Sashaktikaran Programme (Pottery Empowerment) - KVIC",
        "short_description": "Empowers traditional rural potters by distributing motorized modern electric pottery wheels, pug mills, and blungers with 100% equipment grant and training.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "Khadi and Village Industries Commission (KVIC)",
        "target_beneficiaries": "Traditional potters, rural clay artisans, SC/ST/OBC artisans, and women pottery workers.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": 150000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Traditional Potters, Clay Craftsmen, Terracotta Artisans",
        "business_type": "Manufacturing, Handicrafts",
        "project_type": "Eco-friendly clay products, terracotta pottery, earthen kulhads, decorative ceramic crafts",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Free equipment kit worth ₹20,000 to ₹50,000 per potter.",
        "min_loan_amount": 15000.0,
        "max_loan_amount": 50000.0,
        "financial_assistance": "100% free distribution of electric pottery wheels and cluster pug-mills by KVIC.",
        "subsidy_details": "100% grant on modern motorized pottery wheel and toolkit.",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 50000.0,
        "interest_rate": "Nil (100% Grant)",
        "margin_money": "Nil (Zero promoter contribution)",
        "repayment_period": "Not applicable",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 50000.0,
        "benefits": "Quadruples daily pottery production, eliminates physical strain of manual wheels, provides market tie-ups with Indian Railways for kulhads.",
        "required_documents": "Aadhaar Card, Traditional potter community certificate / self-declaration attested by Gram Panchayat, Bank passbook, Passport-size photo.",
        "application_mode": "Offline via State KVIC Office / District Industries Centre",
        "application_steps": "1. Approach local KVIC State/Divisional office or DIC. 2. Submit application form along with traditional potter identity proof. 3. Join KVIC 10-day modern pottery skill development batch. 4. Collect brand new electric pottery wheel upon certificate handover.",
        "official_application_portal": "https://www.kviconline.gov.in/",
        "application_portal_name": "KVIC Gramodyog Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.kviconline.gov.in/",
        "tracking_instructions": "Contact the nearest KVIC Divisional Office with enrollment number.",
        "channel_partner_requirement": True,
        "channel_partner_types": "KVIC State Offices, District Industries Centres (DIC), Khadi Institutions",
        "official_helpline": "022-26711586",
        "official_email": "kumbhar.kvic@gov.in",
        "official_source_url": "https://www.kvic.gov.in/",
        "official_guideline_url": "https://www.kvic.gov.in/kumbhar-guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "LEATHER-KVIC-38",
        "official_scheme_name": "Leather Artisans Empowerment Scheme - KVIC",
        "short_description": "Provides modern shoe-making toolkits and heavy-duty sewing machines with 100% grant to marginalized traditional leather artisans and cobblers.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "Khadi and Village Industries Commission (KVIC)",
        "target_beneficiaries": "Traditional cobblers, leather craft workers, SC community leather artisans, and rural footwear makers.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": 150000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Cobblers, Leather Artisans, Footwear Repairers, Leather Goods Makers",
        "business_type": "Manufacturing, Service",
        "project_type": "Leather footwear manufacturing, shoe repairing, bag and leather accessories production",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Free modern footwear toolkits and machines worth ₹30,000 to ₹45,000.",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 45000.0,
        "financial_assistance": "100% equipment grant including motorized stitching machines, grinder motors, and toolkits.",
        "subsidy_details": "100% grant assistance under Gramodyog Vikas Yojana (GVY).",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 45000.0,
        "interest_rate": "Nil (100% Grant)",
        "margin_money": "Nil.",
        "repayment_period": "Not applicable",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 45000.0,
        "benefits": "Free modern heavy-duty shoe sewing machine, high quality leather cutting tools, 50-70% income increase.",
        "required_documents": "Aadhaar Card, SC/OBC Certificate (or Gram Panchayat verification of traditional leather trade), Bank Passbook, Passport-size photo.",
        "application_mode": "Offline via State KVIC Office / DIC",
        "application_steps": "1. Register at District KVIC office or partner NGO. 2. Verify identity as practicing leather artisan. 3. Attend 5-day skill upgradation workshop on contemporary design. 4. Receive modern leather toolkit and sewing machine.",
        "official_application_portal": "https://www.kviconline.gov.in/",
        "application_portal_name": "KVIC Gramodyog Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.kviconline.gov.in/",
        "tracking_instructions": "Track status at District Industries Centre (DIC) or KVIC State Office.",
        "channel_partner_requirement": True,
        "channel_partner_types": "KVIC State Offices, District Industries Centres, Leather Artisan Cooperatives",
        "official_helpline": "022-26711002",
        "official_email": "leather.kvic@gov.in",
        "official_source_url": "https://www.kvic.gov.in/",
        "official_guideline_url": "https://www.kvic.gov.in/leather-artisan-guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "GVY-KVIC-39",
        "official_scheme_name": "Gramodyog Vikas Yojana (GVY) - Village Industry Clusters",
        "short_description": "Promotes village industries by providing common facility centers, modern production machinery, and marketing support for agarbatti, handmade paper, and bio-waste crafts.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "Khadi and Village Industries Commission (KVIC)",
        "target_beneficiaries": "Rural artisans, SHG women, micro-entrepreneurs, unemployed rural youth.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": 200000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Rural Artisans, SHG Members, Agarbatti Workers, Village Cottage Craftsmen",
        "business_type": "Manufacturing",
        "project_type": "Agarbatti making, handmade paper, waste-to-wealth crafts, natural fibre products",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Subsidy support up to ₹10 Lakh for cluster machinery and individual setups.",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 1000000.0,
        "financial_assistance": "Subsidized automated machinery distribution and raw material bank access.",
        "subsidy_details": "75% to 90% subsidy on automatic agarbatti machines and processing machinery.",
        "subsidy_percentage": 75.0,
        "max_subsidy_amount": 750000.0,
        "interest_rate": "Nil for subsidy portion; bank rates for remaining loan.",
        "margin_money": "10% to 25% promoter contribution.",
        "repayment_period": "3 to 5 years",
        "moratorium": "3 months",
        "collateral_requirement": "Hypothecation of machinery.",
        "project_cost_limit": 1000000.0,
        "benefits": "Automated production equipment, raw material supply guarantee from KVIC, local employment generation.",
        "required_documents": "Aadhaar Card, SHG Registration or Individual Identity, Bank Passbook, Residence Certificate.",
        "application_mode": "Offline via KVIC Field Offices / State Khadi Boards",
        "application_steps": "1. Approach State KVIC or KVIB office. 2. Submit proposal for Agarbatti / Village Industry unit. 3. Undergo technical training at KVIC centre. 4. Machinery delivered with on-site installation.",
        "official_application_portal": "https://www.kviconline.gov.in/",
        "application_portal_name": "KVIC Gramodyog Online Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.kviconline.gov.in/",
        "tracking_instructions": "Inquire with KVIC State Director or District Industries Officer.",
        "channel_partner_requirement": True,
        "channel_partner_types": "KVIC State Offices, State Khadi & Village Industries Boards (KVIB)",
        "official_helpline": "022-26713601",
        "official_email": "gvy.kvic@gov.in",
        "official_source_url": "https://www.kvic.gov.in/",
        "official_guideline_url": "https://www.kvic.gov.in/gvy-scheme-guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "SFURTI-MSME-40",
        "official_scheme_name": "Scheme of Fund for Regeneration of Traditional Industries (SFURTI)",
        "short_description": "Revitalizes traditional artisan clusters by providing grants up to ₹2.5 Crore (Regular) and ₹5 Crore (Major) to build Common Facility Centres (CFC) and procure modern machinery.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "Infrastructure and Public Procurement Division",
        "target_beneficiaries": "Artisan collectives, Traditional craft clusters, SHG federations, FPOs, Village co-operatives.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Traditional Weavers, Handicraft Artisans, Bamboo Workers, Coir Makers, Pottery Workers",
        "business_type": "Manufacturing, Handicrafts",
        "project_type": "Artisan cluster development, Common Facility Centre (CFC), advanced machinery, packaging, e-commerce branding",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Grant assistance up to ₹2.50 Crore (for up to 500 artisans) and up to ₹5.00 Crore (for over 500 artisans).",
        "min_loan_amount": 10000000.0,
        "max_loan_amount": 50000000.0,
        "financial_assistance": "100% government grant for soft interventions (design & training) and up to 90% grant for Common Facility Centres (CFC).",
        "subsidy_details": "Up to 90% grant for CFC hard interventions and 100% for soft interventions funded by MoMSME.",
        "subsidy_percentage": 90.0,
        "max_subsidy_amount": 50000000.0,
        "interest_rate": "Nil (Government Grant)",
        "margin_money": "10% contribution by Cluster Implementing Agency / Special Purpose Vehicle (SPV).",
        "repayment_period": "Not applicable (Grant)",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 50000000.0,
        "benefits": "State-of-the-art Common Facility Centre, global packaging and branding, direct export linkages for rural craftspersons.",
        "required_documents": "Cluster Diagnostic Study Report (DSR), Detailed Project Report (DPR), SPV Registration documents, Artisan list with Aadhaar numbers, Land title for CFC.",
        "application_mode": "Online on SFURTI Portal",
        "application_steps": "1. Cluster Implementing Agency prepares Diagnostic Study Report (DSR). 2. Submit proposal on sfurti.msme.gov.in. 3. Technical Agency (TA) appraises proposal. 4. Scheme Steering Committee (SSC) grants final approval. 5. Funds released in 3 tranches to project SPV account.",
        "official_application_portal": "https://sfurti.msme.gov.in/",
        "application_portal_name": "SFURTI MoMSME Portal",
        "application_tracking_available": True,
        "tracking_url": "https://sfurti.msme.gov.in/",
        "tracking_instructions": "Enter Cluster ID on sfurti.msme.gov.in to check appraisal status, SSC approval, and grant disbursement.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Nodal Agencies (KVIC, Coir Board, IIE Guwahati, NIMSME), Technical Agencies (TA)",
        "official_helpline": "011-23061543",
        "official_email": "sfurti.msme@nic.in",
        "official_source_url": "https://sfurti.msme.gov.in/",
        "official_guideline_url": "https://sfurti.msme.gov.in/SFURTI/Home.aspx",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "ASPIRE-MSME-41",
        "official_scheme_name": "ASPIRE - Scheme for Promotion of Innovation, Rural Industry & Entrepreneurship",
        "short_description": "Sets up Livelihood Business Incubators (LBI) with grants up to ₹1 Crore to train rural youth and facilitate self-sustaining agro-rural enterprise startups.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "SME Division",
        "target_beneficiaries": "Rural youth, aspiring entrepreneurs, farmers, technical institutions, and rural incubator graduates.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 45 years",
        "minimum_age": 18,
        "maximum_age": 45,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Rural Youth, Agri-graduates, Aspiring Micro-manufacturers, Innovators",
        "business_type": "Manufacturing, Agri-Allied, Service",
        "project_type": "Agro-processing, food preservation, rural engineering, automation, local herbal products",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Grant up to ₹1 Crore for government LBI (up to ₹50 Lakh for private LBI) and seed fund support up to ₹1 Crore.",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 10000000.0,
        "financial_assistance": "100% grant for plant and machinery to set up Livelihood Business Incubator.",
        "subsidy_details": "100% one-time grant up to ₹1 Crore for government institutions; 50% up to ₹50 Lakh for private entities.",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 10000000.0,
        "interest_rate": "Nil (Government Grant)",
        "margin_money": "Nil for government institutions; 50% for private entities.",
        "repayment_period": "Not applicable",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 10000000.0,
        "benefits": "Practical hands-on machinery training for rural entrepreneurs, ready-to-use incubation infrastructure, seed fund linkage.",
        "required_documents": "Detailed Project Report (DPR), Entity registration documents, Infrastructure and power clearance, Bank account details.",
        "application_mode": "Online on ASPIRE Portal",
        "application_steps": "1. Visit aspire.msme.gov.in. 2. Submit proposal for Livelihood Business Incubator (LBI) or Technology Business Incubator (TBI). 3. Project Screening Committee (PSC) reviews proposal. 4. PAC sanctions grant. 5. Trainees graduate with bankable business proposals.",
        "official_application_portal": "https://aspire.msme.gov.in/",
        "application_portal_name": "ASPIRE MoMSME Portal",
        "application_tracking_available": True,
        "tracking_url": "https://aspire.msme.gov.in/",
        "tracking_instructions": "Check proposal tracking section on aspire.msme.gov.in using application login.",
        "channel_partner_requirement": True,
        "channel_partner_types": "NSIC, KVIC, Coir Board, State Government Institutions, Technical Universities",
        "official_helpline": "011-23062230",
        "official_email": "aspire-msme@gov.in",
        "official_source_url": "https://aspire.msme.gov.in/",
        "official_guideline_url": "https://aspire.msme.gov.in/ASPIRE/Guidelines.aspx",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "HWMUDRA-TEX-42",
        "official_scheme_name": "Handloom Weavers Mudra Scheme",
        "short_description": "Provides concessional working capital loans up to ₹2 Lakh at an effective interest rate of 6% with margin money assistance up to ₹10,000 for weavers.",
        "ministry": "Ministry of Textiles",
        "department": "Office of the Development Commissioner for Handlooms",
        "target_beneficiaries": "Handloom weavers, master weavers, handloom allied workers, and handloom SHG members.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Handloom Weavers, Yarn Winders, Dyers, Pattern Makers",
        "business_type": "Manufacturing, Handlooms",
        "project_type": "Yarn purchase, dyes and chemicals, loom repairs, working capital for weaving cycle",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Concessional credit up to ₹2,00,000 as term loan / working capital.",
        "min_loan_amount": 25000.0,
        "max_loan_amount": 200000.0,
        "financial_assistance": "Subsidized bank loan with 6% interest subvention and upfront margin money assistance of ₹10,000 per weaver.",
        "subsidy_details": "Margin money assistance @ 20% of loan amount (max ₹10,000 for individual weavers; up to ₹20,00,000 for cooperatives) + 6% interest subvention for 3 years.",
        "subsidy_percentage": 20.0,
        "max_subsidy_amount": 10000.0,
        "interest_rate": "Effective 6% p.a. (Excess bank interest borne by Ministry of Textiles)",
        "margin_money": "Covered by Government margin money assistance up to ₹10,000.",
        "repayment_period": "3 years",
        "moratorium": "Not applicable (Revolving cash credit / term loan)",
        "collateral_requirement": "No collateral or third-party guarantee required. Covered under Credit Guarantee scheme.",
        "project_cost_limit": 200000.0,
        "benefits": "6% concessional interest rate, ₹10,000 upfront free margin money, RuPay Weaver Credit Card for instant raw material purchases.",
        "required_documents": "Weaver Photo Identity Card (issued by DC Handlooms), Aadhaar Card, Bank Passbook, Proof of Weaving Occupation.",
        "application_mode": "Offline via Weavers' Service Centre (WSC) / District Handloom Officer or Online on JanSamarth",
        "application_steps": "1. Approach local Weavers' Service Centre (WSC) or Assistant Director of Handlooms. 2. Verify Weaver ID Card. 3. Fill Mudra loan application form. 4. Forwarded to partner commercial bank. 5. Margin money credited upfront and RuPay Weaver Mudra card issued.",
        "official_application_portal": "https://www.handlooms.nic.in/",
        "application_portal_name": "Development Commissioner for Handlooms Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.handlooms.nic.in/",
        "tracking_instructions": "Check application progress at the local Weavers' Service Centre (WSC) or State Directorate of Handlooms.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Weavers' Service Centres (WSC), Commercial Banks, District Handloom Offices, State Handloom Apex Societies",
        "official_helpline": "1800-208-9988",
        "official_email": "dchandlooms@nic.in",
        "official_source_url": "https://www.handlooms.nic.in/",
        "official_guideline_url": "https://www.handlooms.nic.in/writereaddata/Weaver_Mudra_Scheme.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "NHDP-WEAVERS-43",
        "official_scheme_name": "National Handloom Development Programme (NHDP) - Block Level Clusters",
        "short_description": "Supports handloom weaver clusters with financial assistance up to ₹2 Crore per cluster for common facility centres, technological upgradation, and lighting units.",
        "ministry": "Ministry of Textiles",
        "department": "Office of the Development Commissioner for Handlooms",
        "target_beneficiaries": "Handloom weavers, weaver SHGs, cooperative societies, and marginalized rural craftspeople.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Handloom Weavers, Reelers, Spinners, Cluster Workers",
        "business_type": "Manufacturing, Handlooms",
        "project_type": "Weaver cluster development, jacquard installation, pneumatic loom attachments, yarn depot setup",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Financial assistance up to ₹2.00 Crore per Block Level Cluster.",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 20000000.0,
        "financial_assistance": "Direct government grant for common infrastructure, 90% subsidy for individual loom upgradation.",
        "subsidy_details": "90% subsidy on jacquard, dobby, motorized warp beam, and solar lighting units; 100% grant for CFC construction.",
        "subsidy_percentage": 90.0,
        "max_subsidy_amount": 20000000.0,
        "interest_rate": "Nil (Government Grant)",
        "margin_money": "10% beneficiary contribution for individual loom accessories.",
        "repayment_period": "Not applicable",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 20000000.0,
        "benefits": "90% subsidized modern looms and jacquards, free design CAD training, direct raw material supply at Mill Gate Price Scheme.",
        "required_documents": "Weaver Identity Card (Pehchan Card), Aadhaar Card, Bank Account Details, Cluster Membership Proof.",
        "application_mode": "Offline via State Directorate of Handlooms / Weavers Service Centre",
        "application_steps": "1. Cluster proposal formulated by State Directorate of Handlooms. 2. Weavers enroll through their primary cooperative or SHG. 3. DC Handlooms sanctions Block Level Cluster. 4. Modern equipment installed directly at weaver work-shed.",
        "official_application_portal": "https://www.handlooms.nic.in/",
        "application_portal_name": "DC Handlooms Official Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.handlooms.nic.in/",
        "tracking_instructions": "Inquire with Weavers' Service Centre or District Handloom Officer.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Weavers Service Centres (WSC), State Handloom Directorates, National Handloom Development Corporation (NHDC)",
        "official_helpline": "1800-208-9988",
        "official_email": "nhdp.handlooms@nic.in",
        "official_source_url": "https://www.handlooms.nic.in/",
        "official_guideline_url": "https://www.handlooms.nic.in/writereaddata/NHDP_Guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "AHVY-CRAFTS-44",
        "official_scheme_name": "Ambedkar Hastshilp Vikas Yojana (AHVY)",
        "short_description": "Promotes holistic development of marginalized handicraft artisan clusters through self-reliance, modern toolkits, design workshops, and marketing emporiums.",
        "ministry": "Ministry of Textiles",
        "department": "Office of the Development Commissioner (Handicrafts)",
        "target_beneficiaries": "SC, ST, OBC, women, and minority handicraft artisans living in rural and urban craft clusters.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Handicraft Artisans, Wood Carvers, Metal Craftsmen, Embroidery Workers, Terracotta Sculptors",
        "business_type": "Handicrafts, Manufacturing",
        "project_type": "Handicraft cluster development, artisan mobilization, common facility center, design incubation",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Grant assistance up to ₹1.50 Crore per artisan cluster.",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 15000000.0,
        "financial_assistance": "100% grant for cluster diagnostic studies, design workshops, and toolkits distribution.",
        "subsidy_details": "100% grant for modern toolkits, training stipends, and participation in Dastkar / Gandhi Shilp Bazaars.",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 15000000.0,
        "interest_rate": "Nil (Government Grant)",
        "margin_money": "Nil.",
        "repayment_period": "Not applicable",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 15000000.0,
        "benefits": "Free modern tools, daily training stipend of ₹300/day during workshops, free stall allocation at national craft exhibitions.",
        "required_documents": "Pehchan Artisan ID Card, Aadhaar Card, Bank Passbook, Proof of craft trade.",
        "application_mode": "Offline via Assistant Director (Handicrafts) / Service Centre or Online on DC Handicrafts portal",
        "application_steps": "1. Register on DC Handicrafts portal to obtain Pehchan ID card. 2. Join local AHVY cluster through NGO / Implementing Agency. 3. Attend design development and technical training workshop. 4. Receive modern toolkit and direct exhibition pass.",
        "official_application_portal": "https://www.handicrafts.nic.in/",
        "application_portal_name": "DC Handicrafts Official Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.handicrafts.nic.in/",
        "tracking_instructions": "Enter Pehchan Card Number on handicrafts.nic.in to verify artisan enrollment and scheme benefits.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Field Offices of DC Handicrafts, Central / State Handicrafts Corporations, Registered Artisan Societies",
        "official_helpline": "1800-208-4800",
        "official_email": "dchandicrafts@nic.in",
        "official_source_url": "https://www.handicrafts.nic.in/",
        "official_guideline_url": "https://www.handicrafts.nic.in/writereaddata/AHVY_Guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "MAHILA-COIR-45",
        "official_scheme_name": "Mahila Coir Yojana (Coir Board)",
        "short_description": "Women-centric scheme providing 75% subsidy on motorized traditional and electronic ratts for rural women artisans to spin coir yarn.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "Coir Board",
        "target_beneficiaries": "Rural women artisans, women SHGs in coconut producing coastal and rural regions.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Coir Spinners, Rural Women Artisans, SHG Members",
        "business_type": "Manufacturing",
        "project_type": "Coir yarn spinning, coir mat production, coconut fibre value-addition",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Subsidy on motorized ratt / electronic spinning unit worth ₹25,000 to ₹50,000.",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 50000.0,
        "financial_assistance": "75% capital subsidy on cost of motorized spinning ratts / motorized traditional ratts.",
        "subsidy_details": "75% capital subsidy provided by Coir Board; remaining 25% paid by beneficiary or bank loan.",
        "subsidy_percentage": 75.0,
        "max_subsidy_amount": 37500.0,
        "interest_rate": "Nil on subsidy portion; bank MSME rate if 25% is funded via bank loan.",
        "margin_money": "25% beneficiary contribution.",
        "repayment_period": "2 to 3 years if bank financed.",
        "moratorium": "1 month",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 50000.0,
        "benefits": "75% equipment subsidy, 2-month certified training with stipend of ₹3,000/month, eliminates physical fatigue of manual spinning.",
        "required_documents": "Aadhaar Card, Proof of Coir Board training completion, Bank Account details, Passport-size photo.",
        "application_mode": "Offline via Coir Board Regional Offices / Field Training Centres",
        "application_steps": "1. Undergo 2 months coir yarn spinning training at Coir Board training centre. 2. Apply for motorized ratt subsidy. 3. Deposit 25% margin money. 4. Coir Board delivers certified motorized spinning ratt directly.",
        "official_application_portal": "https://coirboard.gov.in/",
        "application_portal_name": "Coir Board Official Portal",
        "application_tracking_available": True,
        "tracking_url": "https://coirboard.gov.in/",
        "tracking_instructions": "Contact Coir Board Sub-Regional Office or District Industries Centre.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Coir Board Regional Offices, District Industries Centres (DIC), State Coir Federations",
        "official_helpline": "0484-2351988",
        "official_email": "coirboard@nic.in",
        "official_source_url": "https://coirboard.gov.in/",
        "official_guideline_url": "https://coirboard.gov.in/wp-content/uploads/2019/12/Mahila-Coir-Yojana.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "CUY-COIR-46",
        "official_scheme_name": "Coir Udyami Yojana (CUY)",
        "short_description": "Credit-linked subsidy scheme providing 25% capital subsidy for setting up coir processing and manufacturing units with project cost up to ₹10 Lakh.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "Coir Board",
        "target_beneficiaries": "Entrepreneurs, rural youth, women, SHGs, and cooperatives setting up coir micro-enterprises.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Coir Entrepreneurs, Rural Manufacturers, SHG Members",
        "business_type": "Manufacturing",
        "project_type": "Coir pith briquetting, coir geo-textiles, coir mattress making, curled coir rope units",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Bank loan of 55% of project cost (Project cost up to ₹10 Lakh).",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 1000000.0,
        "financial_assistance": "25% government subsidy + 55% bank term loan + 20% promoter contribution (5% for SC/ST/Women).",
        "subsidy_details": "25% capital subsidy of project cost (max ₹2.50 Lakh) credited directly to bank account.",
        "subsidy_percentage": 25.0,
        "max_subsidy_amount": 250000.0,
        "interest_rate": "Commercial bank lending rate on MSME credit.",
        "margin_money": "5% for SC/ST/Women/NER; 10% to 20% for General category.",
        "repayment_period": "Up to 7 years",
        "moratorium": "6 months",
        "collateral_requirement": "Covered under CGTMSE credit guarantee.",
        "project_cost_limit": 1000000.0,
        "benefits": "25% capital subsidy, zero collateral under CGTMSE, Coir Board technical incubation and marketing assistance.",
        "required_documents": "Detailed Project Report (DPR), Aadhaar Card, PAN Card, Category Certificate (if SC/ST), Premises proof / lease.",
        "application_mode": "Online on Coir Board Portal or via DIC",
        "application_steps": "1. Submit online application on coirboard.gov.in. 2. Coir Board scrutinizes DPR. 3. Forwarded to designated bank for term loan sanction. 4. Bank disburses loan and claims 25% subsidy from Coir Board.",
        "official_application_portal": "https://coirboard.gov.in/",
        "application_portal_name": "Coir Board National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://coirboard.gov.in/",
        "tracking_instructions": "Check status at Coir Board Regional Office with application registration code.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Coir Board, Public Sector Banks, District Industries Centres (DIC)",
        "official_helpline": "0484-2351807",
        "official_email": "cuy.coirboard@nic.in",
        "official_source_url": "https://coirboard.gov.in/",
        "official_guideline_url": "https://coirboard.gov.in/cuy-guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "SILK-SAMAGRA-47",
        "official_scheme_name": "Silk Samagra 2 (Central Silk Board)",
        "short_description": "Comprehensive scheme providing 50% to 75% capital subsidies for mulberry/vanya plantation, rearing sheds, automatic silk reeling machines, and grainages.",
        "ministry": "Ministry of Textiles",
        "department": "Central Silk Board (CSB)",
        "target_beneficiaries": "Sericulture farmers, silkworm rearers, reelers, weavers, SC/ST tribal farm families.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Sericulture Farmers, Silkworm Rearers, Silk Reelers, Twisters",
        "business_type": "Agri-Allied, Manufacturing",
        "project_type": "Silkworm rearing houses, solar/electric motorized reeling basins, mulberry plantation, disinfection equipment",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Subsidy assistance up to ₹4,50,000 for rearing house and up to ₹35 Lakh for Automatic Reeling Units (ARM).",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 3500000.0,
        "financial_assistance": "Direct Benefit Transfer (DBT) subsidy of 50% (General) and 75% (SC/ST/NER) of component unit cost.",
        "subsidy_details": "75% subsidy for SC/ST and women rearers; 50% for others on rearing house construction and reeling machines.",
        "subsidy_percentage": 75.0,
        "max_subsidy_amount": 2625000.0,
        "interest_rate": "Commercial bank lending rate on loan component.",
        "margin_money": "25% (15% for SC/ST) beneficiary contribution.",
        "repayment_period": "5 to 7 years if bank financed.",
        "moratorium": "6 months",
        "collateral_requirement": "Hypothecation of sericulture machinery.",
        "project_cost_limit": 3500000.0,
        "benefits": "High 75% subsidy for marginalized families, regular monthly cash flows from 5-6 silk cocoon crops per year, guaranteed cocoon market.",
        "required_documents": "Aadhaar Card, Land records showing mulberry cultivation, Caste Certificate (for SC/ST), Bank Passbook, Training Certificate from CSB/State Sericulture Dept.",
        "application_mode": "Offline via District Sericulture Officer / State Directorate of Sericulture",
        "application_steps": "1. Approach District Sericulture Officer (DSO). 2. Register farm plot for sericulture. 3. Complete silkworm rearing training. 4. Inspect rearing shed construction. 5. Subsidy released directly to bank account via DBT.",
        "official_application_portal": "https://csb.gov.in/",
        "application_portal_name": "Central Silk Board National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://csb.gov.in/",
        "tracking_instructions": "Check status at District Sericulture Department with Farmer Registration Number.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Sericulture Offices, Central Silk Board Research Stations, Commercial Banks",
        "official_helpline": "080-26282699",
        "official_email": "silksamagra.csb@nic.in",
        "official_source_url": "https://csb.gov.in/",
        "official_guideline_url": "https://csb.gov.in/schemes-and-services/silk-samagra-2/",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "NSKFDC-GTL-48",
        "official_scheme_name": "NSKFDC General Term Loan (GTL) for Sanitation Workers",
        "short_description": "Provides concessional term loans up to ₹15 Lakh at 6% p.a. interest to Safai Karamcharis, manual scavengers, and their dependents to start viable enterprises.",
        "ministry": "Ministry of Social Justice and Empowerment (MoSJE)",
        "department": "National Safai Karamcharis Finance and Development Corporation (NSKFDC)",
        "target_beneficiaries": "Safai Karamcharis (sanitation workers), identified manual scavengers, and their dependent family members.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": None,
        "income_period": "No income ceiling for Safai Karamcharis as per revised guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Sanitation Workers, Safai Karamcharis, Manual Scavengers, Waste Collectors",
        "business_type": "Manufacturing, Service, Trading, Agri-Allied",
        "project_type": "Transport vehicles, small grocery retail, hardware shops, tailoring, mechanized cleaning enterprise",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹15,00,000 (up to 90% of project cost funded by NSKFDC).",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 1500000.0,
        "financial_assistance": "Term loan up to 90% of project cost at highly concessional interest rate of 6% p.a.",
        "subsidy_details": "Interest concession (effective 6% p.a., with 1% rebate for women) and upfront capital subsidy up to ₹5 Lakh for identified manual scavengers.",
        "subsidy_percentage": 50.0,
        "max_subsidy_amount": 500000.0,
        "interest_rate": "6% p.a. (5% p.a. for women beneficiaries)",
        "margin_money": "Nil for loans up to ₹2 Lakh; 10% for loans above ₹2 Lakh (Promoter contribution max 5%).",
        "repayment_period": "Up to 5 to 7 years",
        "moratorium": "6 months",
        "collateral_requirement": "No third-party collateral required for loans up to ₹2 Lakh.",
        "project_cost_limit": 1500000.0,
        "benefits": "Low 6% interest rate, up to ₹5 Lakh capital subsidy for manual scavengers, EDP skill training, liberated from hazardous work.",
        "required_documents": "Occupation Certificate proving Safai Karamchari / Manual Scavenger status (issued by local municipal body / Gram Panchayat / employer), Aadhaar Card, PAN Card, Bank Passbook, Project Proposal.",
        "application_mode": "Offline via State Channelising Agencies (SCAs) / Regional Rural Banks or Online via NSKFDC",
        "application_steps": "1. Obtain Safai Karamchari identification certificate from local municipality or Gram Panchayat. 2. Apply at State Channelising Agency (SCA) or nominated bank branch. 3. SCA forwards proposal to NSKFDC. 4. NSKFDC releases funds to SCA. 5. SCA disburses loan directly to applicant.",
        "official_application_portal": "https://nskfdc.nic.in/",
        "application_portal_name": "NSKFDC National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://nskfdc.nic.in/",
        "tracking_instructions": "Track status by contacting State Channelising Agency (SCA) or NSKFDC Zonal Office.",
        "channel_partner_requirement": True,
        "channel_partner_types": "State Channelising Agencies (SCAs), Regional Rural Banks (RRBs), Nationalised Banks",
        "official_helpline": "1800-180-3388",
        "official_email": "nskfdc-msje@nic.in",
        "official_source_url": "https://nskfdc.nic.in/",
        "official_guideline_url": "https://nskfdc.nic.in/en/schemes/general-term-loan",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "NSKFDC-MSY-49",
        "official_scheme_name": "NSKFDC Mahila Samridhi Yojana",
        "short_description": "Exclusive micro-credit loan scheme up to ₹1,00,000 at a low 4% p.a. interest rate for female Safai Karamcharis and manual scavengers to start micro-trades.",
        "ministry": "Ministry of Social Justice and Empowerment (MoSJE)",
        "department": "National Safai Karamcharis Finance and Development Corporation (NSKFDC)",
        "target_beneficiaries": "Female Safai Karamcharis, female manual scavengers, and their dependent daughters/wives.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": None,
        "income_period": "No income ceiling as per official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Female Sanitation Workers, Waste Pickers, Scavengers, SHG Members",
        "business_type": "Trading / Retail, Service, Manufacturing",
        "project_type": "Petty retail shops, tea/snack stalls, tailoring, bangle making, beauty parlor, vegetable vending",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Micro-credit up to ₹1,00,000.",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 100000.0,
        "financial_assistance": "Direct micro-credit loan up to ₹1 Lakh at an ultra-low interest rate of 4% p.a.",
        "subsidy_details": "Interest subsidy effectively reducing interest to 4% p.a.; capital subsidy for manual scavenger dependents up to ₹50,000.",
        "subsidy_percentage": 50.0,
        "max_subsidy_amount": 50000.0,
        "interest_rate": "4% p.a.",
        "margin_money": "Nil (100% financed by NSKFDC).",
        "repayment_period": "Up to 3 to 4 years",
        "moratorium": "3 months",
        "collateral_requirement": "No collateral or third-party guarantee required.",
        "project_cost_limit": 100000.0,
        "benefits": "Ultra-low 4% interest rate, zero collateral, quick micro-disbursement through SHGs or SCAs, helps women escape generational sanitation bondage.",
        "required_documents": "Aadhaar Card, Safai Karamchari certificate / Municipal worker verification, Bank passbook, Passport photograph.",
        "application_mode": "Offline via State Channelising Agency (SCA) / Women SHG / RRB",
        "application_steps": "1. Approach local SCA or partner Microfinance Institution / RRB. 2. Submit Mahila Samridhi application with Safai Karamchari certificate. 3. Quick verification and sanction by SCA. 4. Direct disbursement into applicant's Aadhaar-linked bank account.",
        "official_application_portal": "https://nskfdc.nic.in/",
        "application_portal_name": "NSKFDC Portal",
        "application_tracking_available": True,
        "tracking_url": "https://nskfdc.nic.in/",
        "tracking_instructions": "Contact the District SCA Officer or call NSKFDC toll-free helpline.",
        "channel_partner_requirement": True,
        "channel_partner_types": "State Channelising Agencies (SCAs), Microfinance Institutions, Regional Rural Banks",
        "official_helpline": "1800-180-3388",
        "official_email": "nskfdc-msje@nic.in",
        "official_source_url": "https://nskfdc.nic.in/",
        "official_guideline_url": "https://nskfdc.nic.in/en/schemes/mahila-samridhi-yojana",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "NSKFDC-SUY-50",
        "official_scheme_name": "NSKFDC Swachhta Udyami Yojana (SUY) - Mechanised Sanitation Equipment",
        "short_description": "Provides loans up to ₹50 Lakh at 4% to 6% interest for sanitation workers to purchase mechanized cleaning equipment, vacuum suction tankers, and garbage compactor trucks.",
        "ministry": "Ministry of Social Justice and Empowerment (MoSJE)",
        "department": "National Safai Karamcharis Finance and Development Corporation (NSKFDC)",
        "target_beneficiaries": "Safai Karamcharis, manual scavengers, sanitation worker cooperatives, and SHGs.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 60 years",
        "minimum_age": 18,
        "maximum_age": 60,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Sanitation Workers, Sewer Cleaners, Drainage Workers, Waste Transporters",
        "business_type": "Service",
        "project_type": "Procurement of mechanized sewer suction machines, jetting machines, desludging vehicles, pay-and-use community toilet operations",
        "education_requirements": "Valid heavy/commercial motor vehicle driving license (for vehicle-mounted equipment).",
        "loan_amount": "Up to ₹50,00,000 for individual / group units.",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 5000000.0,
        "financial_assistance": "Term loan up to 90% of project cost; capital subsidy under NAMASTE / MoSJE where applicable.",
        "subsidy_details": "Concessional 4% interest rate for women (5% for others) and up to ₹5 Lakh capital subsidy for identified manual scavengers.",
        "subsidy_percentage": 25.0,
        "max_subsidy_amount": 500000.0,
        "interest_rate": "4% p.a. for women; 5% p.a. for men; 6% p.a. for SHGs / Cooperatives",
        "margin_money": "10% (Promoter contribution 5%).",
        "repayment_period": "Up to 7 to 10 years",
        "moratorium": "6 months",
        "collateral_requirement": "Hypothecation of vehicles and cleaning equipment purchased.",
        "project_cost_limit": 5000000.0,
        "benefits": "Eliminates hazardous manual sewer entry, transforms manual scavengers into mechanized entrepreneurs (Sanitation CEOs), assured municipal service contracts.",
        "required_documents": "Safai Karamchari certificate, Commercial driving license (if operating suction trucks), Aadhaar Card, PAN Card, Equipment quotation from OEM dealer, Municipal consent / empanelment letter if available.",
        "application_mode": "Offline via State Channelising Agency / District Municipal Commissioner or Online on NSKFDC portal",
        "application_steps": "1. Obtain vehicle/machinery quotation from authorized manufacturer. 2. Submit application at State Channelising Agency (SCA). 3. Municipal Urban Local Body (ULB) issues tie-up letter for desludging services. 4. NSKFDC releases loan to SCA. 5. Equipment delivered to entrepreneur.",
        "official_application_portal": "https://nskfdc.nic.in/",
        "application_portal_name": "NSKFDC SUY Portal",
        "application_tracking_available": True,
        "tracking_url": "https://nskfdc.nic.in/",
        "tracking_instructions": "Track status through NSKFDC State Channelising Agency or District Social Welfare Officer.",
        "channel_partner_requirement": True,
        "channel_partner_types": "State Channelising Agencies (SCAs), Urban Local Bodies (ULBs), Public Sector Commercial Banks",
        "official_helpline": "1800-180-3388",
        "official_email": "suy.nskfdc@nic.in",
        "official_source_url": "https://nskfdc.nic.in/",
        "official_guideline_url": "https://nskfdc.nic.in/en/schemes/swachhta-udyami-yojana",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    }
]
