# Authoritative Database of Verified Government Schemes - Part 3 (Schemes 76 to 100)
# Sourced exclusively from official Government of India Gazettes, Portals, and Ministry Guidelines

SCHEMES_PART3 = [
    {
        "scheme_id": "BMB-LOAN-76",
        "official_scheme_name": "Bharatiya Mahila Bank Business Loan (SBI)",
        "short_description": "Provides collateral-free working capital and term loans up to ₹20 Lakh with interest rate concessions for women micro and small entrepreneurs.",
        "ministry": "Ministry of Finance",
        "department": "State Bank of India (BMB Division)",
        "target_beneficiaries": "Women entrepreneurs owning manufacturing, retail, or service enterprises.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Women Entrepreneurs, Retailers, Micro Manufacturers, Service Providers",
        "business_type": "Manufacturing, Service, Trading / Retail",
        "project_type": "Small-scale retail, daycare centres, tailoring and garment units, catering services, beauty clinics",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹20,00,000 (Collateral-free under CGTMSE).",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 2000000.0,
        "financial_assistance": "Term loan and cash credit facility with interest rebate of up to 0.50% p.a.",
        "subsidy_details": "0.50% interest rate rebate for women borrowers; zero collateral up to ₹20 Lakh covered under CGTMSE.",
        "subsidy_percentage": 0.5,
        "max_subsidy_amount": 10000.0,
        "interest_rate": "Subsidized bank interest rate (effective ~8.5% - 9.5% p.a.).",
        "margin_money": "10% to 15% promoter contribution.",
        "repayment_period": "Up to 7 years",
        "moratorium": "3 to 6 months",
        "collateral_requirement": "No collateral or third-party guarantee required for loans up to ₹20 Lakh.",
        "project_cost_limit": 2000000.0,
        "benefits": "Zero collateral up to ₹20 Lakh, interest rate concession, dedicated women business advisors, quick loan processing.",
        "required_documents": "Aadhaar Card, PAN Card, Proof of Woman Ownership (>50%), Udyam Registration, Last 6 months bank statement, Quotation for machinery/stock.",
        "application_mode": "Offline at any SBI branch or Online on JanSamarth",
        "application_steps": "1. Approach nearest State Bank of India branch. 2. Request BMB Business Loan application. 3. Enclose business proposal and quotation. 4. Branch evaluates and sanctions loan under CGTMSE guarantee.",
        "official_application_portal": "https://sbi.co.in/",
        "application_portal_name": "State Bank of India Portal",
        "application_tracking_available": True,
        "tracking_url": "https://sbi.co.in/",
        "tracking_instructions": "Inquire with Branch Credit Officer or log on to JanSamarth.",
        "channel_partner_requirement": True,
        "channel_partner_types": "State Bank of India branches across India",
        "official_helpline": "1800-1234 / 1800-2100",
        "official_email": "contactcentre@sbi.co.in",
        "official_source_url": "https://sbi.co.in/",
        "official_guideline_url": "https://sbi.co.in/web/business/sme/special-schemes/bmb-loans",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "MUDRA-TARUN-77",
        "official_scheme_name": "Pradhan Mantri Mudra Yojana (PMMY) - Tarun Plus Tier",
        "short_description": "Offers collateral-free business expansion loans from ₹10 Lakh up to ₹20 Lakh for seasoned entrepreneurs who have previously successfully repaid Tarun loans.",
        "ministry": "Ministry of Finance",
        "department": "Department of Financial Services (DFS)",
        "target_beneficiaries": "Micro and small business owners, women entrepreneurs, manufacturing and service enterprises expanding capacity.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Entrepreneurs, Small Factory Owners, Service Providers, Wholesalers",
        "business_type": "Manufacturing, Service, Trading / Retail",
        "project_type": "Expansion of manufacturing unit, acquisition of modern CNC machinery, commercial vehicle fleet, logistics depot",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "From ₹10,00,001 up to ₹20,00,000 (Enhanced ceiling under Union Budget 2024-25).",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 2000000.0,
        "financial_assistance": "Collateral-free term loan and working capital credit facility.",
        "subsidy_details": "100% guarantee coverage by Credit Guarantee Fund for Micro Units (CGFMU); no processing fee.",
        "subsidy_percentage": 0.0,
        "max_subsidy_amount": 0.0,
        "interest_rate": "Competitive MSME lending rate (approx 8.5% to 11% p.a.).",
        "margin_money": "15% promoter contribution.",
        "repayment_period": "Up to 5 to 7 years",
        "moratorium": "6 months",
        "collateral_requirement": "Nil (Zero collateral security under CGFMU).",
        "project_cost_limit": 2500000.0,
        "benefits": "Enhanced ₹20 Lakh collateral-free limit, no third-party guarantor required, rapid loan processing via JanSamarth or Udyamimitra.",
        "required_documents": "Aadhaar Card, PAN Card, Proof of Previous Mudra loan repayment, Udyam Registration Certificate, Last 12 months bank statement, Projected balance sheet.",
        "application_mode": "Online on JanSamarth / Udyamimitra or Offline at any Bank Branch",
        "application_steps": "1. Visit jansamarth.in or udyamimitra.in. 2. Select Mudra Loan - Tarun Plus category. 3. Enter business financials and Udyam details. 4. Select preferred bank. 5. Bank processes and sanctions loan within 10 working days.",
        "official_application_portal": "https://www.mudra.org.in/",
        "application_portal_name": "MUDRA National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.jansamarth.in/",
        "tracking_instructions": "Log on to jansamarth.in using registered mobile number to check bank lead status and loan sanction letter.",
        "channel_partner_requirement": True,
        "channel_partner_types": "All Scheduled Commercial Banks, Regional Rural Banks (RRBs), Small Finance Banks, NBFCs",
        "official_helpline": "1800-180-1111 / 1800-11-0001",
        "official_email": "help@mudra.org.in",
        "official_source_url": "https://www.mudra.org.in/",
        "official_guideline_url": "https://www.mudra.org.in/Offerings",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "CIF-NRLM-78",
        "official_scheme_name": "DAY-NRLM Community Investment Fund (CIF)",
        "short_description": "Provides revolving livelihood grants up to ₹1,50,000 per Self Help Group to finance individual micro-enterprises and poverty alleviation ventures.",
        "ministry": "Ministry of Rural Development (MoRD)",
        "department": "Rural Livelihoods Division",
        "target_beneficiaries": "Rural women organized in Self Help Groups (SHGs) under Deendayal Antyodaya Yojana - NRLM.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": 150000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Rural Women, SHG Members, Artisans, Small Farm Keepers",
        "business_type": "Manufacturing, Service, Trading / Retail, Agri-Allied",
        "project_type": "Dairy cows, poultry backyard, grocery shop, tailoring machine, vegetable trade, vermicompost",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Revolving fund up to ₹1,50,000 per SHG (individual member loans ₹20,000 to ₹50,000).",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 150000.0,
        "financial_assistance": "Direct grant to Cluster Level Federation (CLF) / Village Organization (VO) for on-lending to SHG members at soft rates.",
        "subsidy_details": "Grant to community-based organization with interest subvention down to 7% (3% on prompt repayment, effective 4% p.a.).",
        "subsidy_percentage": 0.0,
        "max_subsidy_amount": 0.0,
        "interest_rate": "Effective 4% to 7% p.a.",
        "margin_money": "Nil.",
        "repayment_period": "12 to 24 months (Revolving)",
        "moratorium": "1 month",
        "collateral_requirement": "Nil (Mutual trust and peer monitoring).",
        "project_cost_limit": 150000.0,
        "benefits": "Doorstep access to credit without bank bureaucracy, low 4% effective interest rate, community-managed fund.",
        "required_documents": "SHG Passbook, Micro Credit Plan (MCP) resolution, Aadhaar Card, Member photo.",
        "application_mode": "Offline via Village Organization (VO) / Gram Panchayat",
        "application_steps": "1. Prepare Micro Credit Plan (MCP) in SHG meeting. 2. Submit MCP to Village Organization (VO) or Cluster Level Federation. 3. Appraisal and approval by VO executive committee. 4. Cheque / bank transfer issued directly to member.",
        "official_application_portal": "https://aajeevika.gov.in/",
        "application_portal_name": "DAY-NRLM National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://aajeevika.gov.in/",
        "tracking_instructions": "Review VO meeting registers and SRLM MIS ledger.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Village Organizations (VO), Cluster Level Federations (CLF), State Rural Livelihoods Missions (SRLM)",
        "official_helpline": "011-23381611",
        "official_email": "nrlm.cif@gov.in",
        "official_source_url": "https://aajeevika.gov.in/",
        "official_guideline_url": "https://aajeevika.gov.in/sites/default/files/guidelines/CIF_Guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMSVANIDHI-T3-79",
        "official_scheme_name": "PM-SVANidhi Tier 3 (Enhanced Working Capital Loan)",
        "short_description": "Offers enhanced 3rd tranche working capital loans up to ₹50,000 with 7% interest subvention and cashback rewards for digital street vendors.",
        "ministry": "Ministry of Housing and Urban Affairs (MoHUA)",
        "department": "Urban Livelihoods Division",
        "target_beneficiaries": "Urban and peri-urban street vendors who have timely repaid Tier 1 (₹10,000) and Tier 2 (₹20,000) loans.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Urban",
        "occupation_eligibility": "Street Vendors, Hawkers, Thela Operators, Food Cart Owners",
        "business_type": "Trading / Retail, Service",
        "project_type": "Working capital for street vending: vegetables, fruits, street food, garments, footwear, household goods",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Working capital loan up to ₹50,000.",
        "min_loan_amount": 25000.0,
        "max_loan_amount": 50000.0,
        "financial_assistance": "Direct collateral-free bank loan with 7% p.a. interest subvention and up to ₹1,200/year digital cashback.",
        "subsidy_details": "7% per annum interest subvention credited quarterly to bank account + ₹100/month digital transaction cashback.",
        "subsidy_percentage": 7.0,
        "max_subsidy_amount": 3500.0,
        "interest_rate": "Bank lending rate minus 7% interest subvention (effective ~3% - 4% p.a.).",
        "margin_money": "Nil (Zero promoter contribution).",
        "repayment_period": "36 months (3 years)",
        "moratorium": "Nil",
        "collateral_requirement": "Nil (No collateral or third-party guarantee required).",
        "project_cost_limit": 50000.0,
        "benefits": "7% interest subvention, monthly cashback for UPI transactions, builds high CIBIL score, zero collateral.",
        "required_documents": "Vending Certificate / Identity Card issued by ULB (or Letter of Recommendation), Aadhaar Card, PAN Card (optional), Bank Passbook.",
        "application_mode": "Online on PM SVANidhi Portal / Mobile App or via Common Service Centre (CSC)",
        "application_steps": "1. Open pmsvanidhi.mohua.gov.in or SVANidhi App. 2. Login using mobile number linked to Aadhaar. 3. System detects successful Tier 2 closure. 4. Choose preferred lender for Tier 3 (₹50,000). 5. Disbursed directly to savings account within 48 hours.",
        "official_application_portal": "https://pmsvanidhi.mohua.gov.in/",
        "application_portal_name": "PM SVANidhi Portal",
        "application_tracking_available": True,
        "tracking_url": "https://pmsvanidhi.mohua.gov.in/",
        "tracking_instructions": "Enter Application Number or registered Mobile Number on pmsvanidhi.mohua.gov.in to check real-time loan approval and disbursement.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Urban Local Bodies (ULBs), Public Sector Banks, Regional Rural Banks, Small Finance Banks",
        "official_helpline": "1800-11-1979",
        "official_email": "svanidhi-mohua@gov.in",
        "official_source_url": "https://pmsvanidhi.mohua.gov.in/",
        "official_guideline_url": "https://pmsvanidhi.mohua.gov.in/Home/Guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMSVANIDHI-T2-80",
        "official_scheme_name": "PM-SVANidhi Tier 2 (Second Tranche Working Capital)",
        "short_description": "Second tranche collateral-free loan of ₹20,000 with 7% interest subvention for street vendors who have successfully repaid their initial ₹10,000 loan.",
        "ministry": "Ministry of Housing and Urban Affairs (MoHUA)",
        "department": "Urban Livelihoods Division",
        "target_beneficiaries": "Street vendors who repaid Tier 1 loan on time or early.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Urban",
        "occupation_eligibility": "Street Vendors, Fruit Sellers, Thelawalas, Fast Food Vendors",
        "business_type": "Trading / Retail, Service",
        "project_type": "Working capital to replenish inventory, raw materials, fresh produce, and expand street cart stock",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "₹20,000 working capital loan.",
        "min_loan_amount": 20000.0,
        "max_loan_amount": 20000.0,
        "financial_assistance": "Term loan of ₹20,000 with 7% interest subvention and digital cashback up to ₹100 per month.",
        "subsidy_details": "7% per annum interest subvention credited directly to bank account on prompt repayment.",
        "subsidy_percentage": 7.0,
        "max_subsidy_amount": 1400.0,
        "interest_rate": "Effective ~4% p.a. (after 7% subvention)",
        "margin_money": "Nil.",
        "repayment_period": "18 months",
        "moratorium": "Nil",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 20000.0,
        "benefits": "Pre-approved based on prompt repayment of 1st loan, 7% interest rebate, rewards for digital QR transactions.",
        "required_documents": "Vending Certificate / LoR, Aadhaar Card, Bank Passbook.",
        "application_mode": "Online on PM SVANidhi Portal / Mobile App",
        "application_steps": "1. Log on to pmsvanidhi.mohua.gov.in. 2. Select Tier 2 loan option. 3. System validates Tier 1 repayment history. 4. Select bank and accept terms. 5. Funds credited directly to account.",
        "official_application_portal": "https://pmsvanidhi.mohua.gov.in/",
        "application_portal_name": "PM SVANidhi Portal",
        "application_tracking_available": True,
        "tracking_url": "https://pmsvanidhi.mohua.gov.in/",
        "tracking_instructions": "Enter mobile number on PM SVANidhi portal to view Tier 2 sanction status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Commercial Banks, Regional Rural Banks, Small Finance Banks, Urban Local Bodies",
        "official_helpline": "1800-11-1979",
        "official_email": "svanidhi-mohua@gov.in",
        "official_source_url": "https://pmsvanidhi.mohua.gov.in/",
        "official_guideline_url": "https://pmsvanidhi.mohua.gov.in/Home/Guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMSVANIDHI-T1-81",
        "official_scheme_name": "PM-SVANidhi Tier 1 (First Tranche Micro-Credit)",
        "short_description": "Initial collateral-free working capital loan of ₹10,000 at 7% interest subvention to help urban street vendors restart and formalize their micro-trades.",
        "ministry": "Ministry of Housing and Urban Affairs (MoHUA)",
        "department": "Urban Livelihoods Division",
        "target_beneficiaries": "Urban and peri-urban street vendors engaged in vending on or before March 24, 2020.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Urban",
        "occupation_eligibility": "Street Vendors, Hawkers, Cobblers, Tea Sellers, Flower Sellers",
        "business_type": "Trading / Retail, Service",
        "project_type": "Daily working capital for purchasing fruits, vegetables, flowers, street snacks, and small merchandise",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "₹10,000 working capital loan.",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 10000.0,
        "financial_assistance": "Direct working capital loan of ₹10,000 with 7% p.a. interest subvention.",
        "subsidy_details": "7% per annum interest subvention + digital transaction cashback incentive up to ₹1,200 per year.",
        "subsidy_percentage": 7.0,
        "max_subsidy_amount": 700.0,
        "interest_rate": "Effective ~4% p.a. upon regular monthly repayment.",
        "margin_money": "Nil (Zero margin money).",
        "repayment_period": "12 months (1 year)",
        "moratorium": "Nil",
        "collateral_requirement": "Nil (No collateral or guarantor required).",
        "project_cost_limit": 10000.0,
        "benefits": "Fast collateral-free credit, 7% interest rebate, free QR code for digital payments with cashback, opens pathway to ₹20K and ₹50K loans.",
        "required_documents": "Vending Certificate / Identity Card issued by ULB (or Letter of Recommendation from Town Vending Committee), Aadhaar Card, Bank Passbook.",
        "application_mode": "Online on PM SVANidhi Portal / Mobile App or via CSC / Banking Correspondent",
        "application_steps": "1. Visit nearest Common Service Centre (CSC) or log on to pmsvanidhi.mohua.gov.in. 2. Verify Vending Certificate or TVC Letter of Recommendation. 3. Complete e-KYC via Aadhaar OTP. 4. Select nearby bank branch. 5. Loan disbursed into bank account.",
        "official_application_portal": "https://pmsvanidhi.mohua.gov.in/",
        "application_portal_name": "PM SVANidhi Portal",
        "application_tracking_available": True,
        "tracking_url": "https://pmsvanidhi.mohua.gov.in/",
        "tracking_instructions": "Track online using Application Reference Number or registered mobile number on pmsvanidhi.mohua.gov.in.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Urban Local Bodies (ULBs), Scheduled Commercial Banks, Regional Rural Banks, Common Service Centres",
        "official_helpline": "1800-11-1979",
        "official_email": "svanidhi-mohua@gov.in",
        "official_source_url": "https://pmsvanidhi.mohua.gov.in/",
        "official_guideline_url": "https://pmsvanidhi.mohua.gov.in/Home/Guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMKSY-APC-82",
        "official_scheme_name": "PMKSY - Scheme for Creation of Infrastructure for Agro Processing Clusters (APC)",
        "short_description": "Provides grants up to ₹10 Crore (35% to 50% subsidy) to set up modern agro-processing clusters with common infrastructure and processing units in rural areas.",
        "ministry": "Ministry of Food Processing Industries (MoFPI)",
        "department": "Agro Processing Clusters Division",
        "target_beneficiaries": "Entrepreneurs, farmer producer organizations (FPOs), cooperatives, and corporate entities setting up food processing clusters.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Food Processors, Agro-Entrepreneurs, FPO Federations, Cold Chain Operators",
        "business_type": "Manufacturing, Agri-Allied",
        "project_type": "Agro processing cluster: modern packhouse, cold storage, quality testing lab, effluent treatment, steam/power generation",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Grant-in-aid up to ₹10.00 Crore per cluster project.",
        "min_loan_amount": 10000000.0,
        "max_loan_amount": 100000000.0,
        "financial_assistance": "Grant-in-aid of 35% of eligible project cost in General areas and 50% in Difficult / SC/ST / ITDP areas.",
        "subsidy_details": "35% grant (max ₹10 Crore) in general areas; 50% grant (max ₹10 Crore) in North East, Himalayan states, and ITDP notified areas.",
        "subsidy_percentage": 50.0,
        "max_subsidy_amount": 100000000.0,
        "interest_rate": "Commercial bank lending rate on the debt portion.",
        "margin_money": "Minimum 20% promoter equity contribution.",
        "repayment_period": "Up to 7 to 10 years",
        "moratorium": "Up to 2 years",
        "collateral_requirement": "Mortgage of project land and common infrastructure.",
        "project_cost_limit": 100000000.0,
        "benefits": "Up to ₹10 Crore direct grant, common utility infrastructure shared among at least 5 food processing units, minimises post-harvest losses.",
        "required_documents": "Detailed Project Report (DPR), Minimum 10 acres contiguous land title, In-principle bank loan sanction, Environmental clearance, FSSAI registration.",
        "application_mode": "Online on MoFPI Sampada Portal",
        "application_steps": "1. Review Expression of Interest (EoI) on mofpi.gov.in. 2. Submit application with DPR and appraisal report online. 3. Technical Committee (TC) reviews proposal. 4. Inter-Ministerial Approval Committee (IMAC) sanctions grant. 5. Grant released in 4 milestones.",
        "official_application_portal": "https://www.mofpi.gov.in/",
        "application_portal_name": "MoFPI SAMPADA Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.mofpi.gov.in/",
        "tracking_instructions": "Enter Proposal File ID on MoFPI portal to view TC and IMAC sanction status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Scheduled Commercial Banks, NABARD, State Food Processing Agencies",
        "official_helpline": "011-26406500",
        "official_email": "apc-mofpi@gov.in",
        "official_source_url": "https://www.mofpi.gov.in/",
        "official_guideline_url": "https://www.mofpi.gov.in/schemes/pradhan-mantri-kisan-sampada-yojana/creation-infrastructure-agro-processing-clusters",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMKSY-CEFPPC-83",
        "official_scheme_name": "PMKSY - Creation / Expansion of Food Processing Capacities (CEFPPC)",
        "short_description": "Provides capital subsidies of 35% to 50% (up to ₹5 Crore) for establishing new food processing units and modernizing existing units across rural India.",
        "ministry": "Ministry of Food Processing Industries (MoFPI)",
        "department": "CEFPPC Division",
        "target_beneficiaries": "Entrepreneurs, food processors, FPOs, SHGs, and cooperatives.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Food Processors, Agro-Entrepreneurs, Miller Owners, Dairy Processors",
        "business_type": "Manufacturing",
        "project_type": "Fruit & vegetable processing, dairy processing, meat/poultry processing, grains and oilseed milling, ready-to-eat foods",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Grant-in-aid up to ₹5.00 Crore per unit.",
        "min_loan_amount": 5000000.0,
        "max_loan_amount": 50000000.0,
        "financial_assistance": "Capital subsidy of 35% of eligible plant, machinery, and technical civil works (50% for SC/ST and North East).",
        "subsidy_details": "35% capital subsidy (max ₹5 Crore) in general areas; 50% capital subsidy (max ₹5 Crore) in SC/ST, NER, and island territories.",
        "subsidy_percentage": 50.0,
        "max_subsidy_amount": 50000000.0,
        "interest_rate": "Commercial bank lending rate on the loan component.",
        "margin_money": "Minimum 20% promoter equity contribution.",
        "repayment_period": "Up to 7 years",
        "moratorium": "1 year",
        "collateral_requirement": "Mortgage of factory land, building, and machinery.",
        "project_cost_limit": 50000000.0,
        "benefits": "Substantial capital grant up to ₹5 Crore, increases shelf-life of agricultural commodities, creates local rural factory jobs.",
        "required_documents": "Detailed Project Report (DPR), Bank appraisal and sanction letter, Land title deed / lease agreement, Quotations for plant & machinery, FSSAI license / application.",
        "application_mode": "Online on MoFPI Portal",
        "application_steps": "1. Check open EoI notifications on mofpi.gov.in. 2. Submit application online with DPR and bank appraisal. 3. Appraisal by Project Management Agency (PMA). 4. IMAC approves project. 5. Grant released in 3 milestone installments.",
        "official_application_portal": "https://www.mofpi.gov.in/",
        "application_portal_name": "MoFPI SAMPADA Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.mofpi.gov.in/",
        "tracking_instructions": "Check application status on mofpi.gov.in using user credentials.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Scheduled Commercial Banks, Project Management Agencies (PMAs)",
        "official_helpline": "011-26406500",
        "official_email": "cefppc-mofpi@gov.in",
        "official_source_url": "https://www.mofpi.gov.in/",
        "official_guideline_url": "https://www.mofpi.gov.in/schemes/pradhan-mantri-kisan-sampada-yojana/creation-expansion-food-processing-preservation-capacities",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "AHIDF-DAIRY-84",
        "official_scheme_name": "Animal Husbandry Infrastructure Development Fund (AHIDF)",
        "short_description": "Provides 3% interest subvention and up to 25% credit guarantee for individual entrepreneurs, FPOs, and MSMEs setting up modern dairy and meat processing units.",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying (MoFAHD)",
        "department": "Department of Animal Husbandry and Dairying (DAHD)",
        "target_beneficiaries": "Farmer Producer Organizations (FPOs), MSMEs, Section 8 companies, private enterprises, individual entrepreneurs.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Dairy Processors, Livestock Entrepreneurs, Meat Plant Operators, Animal Feed Millers",
        "business_type": "Manufacturing, Agri-Allied",
        "project_type": "Dairy processing plants, milk chilling units, automated animal feed manufacturing, meat processing facilities",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to 90% of project cost funded via bank loan with 3% interest subvention.",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 50000000.0,
        "financial_assistance": "Term loan from scheduled banks with 3% interest subvention for 8 years + up to 25% credit guarantee through NABARD.",
        "subsidy_details": "3% per annum interest subvention for up to 8 years + 25% credit guarantee cover under Credit Guarantee Trust for AHIDF.",
        "subsidy_percentage": 3.0,
        "max_subsidy_amount": 1500000.0,
        "interest_rate": "Bank lending rate minus 3% interest subvention.",
        "margin_money": "10% for MSMEs; 15% for others.",
        "repayment_period": "Up to 10 years",
        "moratorium": "Up to 2 years",
        "collateral_requirement": "Covered under Credit Guarantee Trust for AHIDF up to 25% of loan; primary security of assets.",
        "project_cost_limit": 50000000.0,
        "benefits": "3% interest subvention for 8 years, 25% credit guarantee cover, 2-year moratorium, single-window online clearance.",
        "required_documents": "Detailed Project Report (DPR), Land title documents / lease deed, Bank loan sanction letter, Environmental clearance, FSSAI registration.",
        "application_mode": "Online on AHIDF Portal",
        "application_steps": "1. Visit ahidf.udyamimitra.in. 2. Register as 'Borrower'. 3. Fill online form and upload DPR. 4. Select preferred participating bank. 5. DAHD reviews within 15 days and bank issues sanction.",
        "official_application_portal": "https://ahidf.udyamimitra.in/",
        "application_portal_name": "AHIDF Udyamimitra Portal",
        "application_tracking_available": True,
        "tracking_url": "https://ahidf.udyamimitra.in/",
        "tracking_instructions": "Log on to ahidf.udyamimitra.in to track Ministry approval, Bank sanction, and subvention claims.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Scheduled Commercial Banks, NABARD, SIDBI",
        "official_helpline": "011-23381012",
        "official_email": "ahidf-dahd@nic.in",
        "official_source_url": "https://dahd.nic.in/",
        "official_guideline_url": "https://dahd.nic.in/schemes/programmes/ahidf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMMSY-DEEPSEA-85",
        "official_scheme_name": "PMMSY - Support for Deep Sea Fishing Vessels",
        "short_description": "Provides 40% (General) to 60% (SC/ST/Women) subsidy up to ₹48 Lakh for traditional fishers to acquire modern deep-sea tuna longliner fishing vessels.",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying (MoFAHD)",
        "department": "Department of Fisheries",
        "target_beneficiaries": "Traditional coastal fishermen, fishers' self-help groups, fisheries cooperatives, SC/ST marine fishers.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Coastal States & UTs (Pan-India)",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Marine Fishers, Traditional Fishermen, Trawler Operators, Fisheries SHGs",
        "business_type": "Agri-Allied, Service",
        "project_type": "Acquisition of deep-sea fishing vessel, motorized tuna longliner, onboard refrigerated seawater system",
        "education_requirements": "Valid marine fishing license / biometric identity card issued by coastal state.",
        "loan_amount": "Unit cost up to ₹80,00,000 for modern deep-sea vessel.",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 8000000.0,
        "financial_assistance": "Direct back-ended capital subsidy of 40% (General) or 60% (SC/ST/Women) of vessel cost.",
        "subsidy_details": "40% subsidy (up to ₹32 Lakh) for General category; 60% subsidy (up to ₹48 Lakh) for SC, ST, and Women fishers.",
        "subsidy_percentage": 60.0,
        "max_subsidy_amount": 4800000.0,
        "interest_rate": "Commercial bank lending rate on the loan portion.",
        "margin_money": "10% for SC/ST/Women; 20% for General category.",
        "repayment_period": "Up to 7 to 10 years",
        "moratorium": "Up to 12 months",
        "collateral_requirement": "Hypothecation and maritime insurance of the deep-sea fishing vessel.",
        "project_cost_limit": 8000000.0,
        "benefits": "Huge subsidy up to ₹48 Lakh, enables harvesting high-value oceanic tuna and pelagic species, modern safety and navigation equipment.",
        "required_documents": "Marine Fisher Biometric ID Card, Coastal Fishing License, Aadhaar Card, Bank Account details, Caste certificate (if SC/ST), Vessel shipyard quotation.",
        "application_mode": "Offline via District Fisheries Office / State Department of Fisheries",
        "application_steps": "1. Approach local Assistant Director of Fisheries. 2. Submit application with boat quotation and fishing license. 3. State Fisheries Directorate scrutinizes proposal. 4. Sanction issued and subsidy released in tranches aligned with boat construction.",
        "official_application_portal": "https://pmmsy.dof.gov.in/",
        "application_portal_name": "PMMSY Portal",
        "application_tracking_available": True,
        "tracking_url": "https://pmmsy.dof.gov.in/",
        "tracking_instructions": "Contact the District Fisheries Office or log in on pmmsy.dof.gov.in.",
        "channel_partner_requirement": True,
        "channel_partner_types": "State Fisheries Departments, National Fisheries Development Board (NFDB), Commercial Banks",
        "official_helpline": "1800-425-1660",
        "official_email": "pmmsy-deepsea@dof.gov.in",
        "official_source_url": "https://pmmsy.dof.gov.in/",
        "official_guideline_url": "https://pmmsy.dof.gov.in/guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "PMMSY-ORNAMENTAL-86",
        "official_scheme_name": "PMMSY - Backyard Ornamental Fish Rearing Units",
        "short_description": "Provides 40% to 60% capital subsidy (up to ₹1.80 Lakh) to rural women, SHGs, and youth to establish low-maintenance backyard ornamental fish breeding tanks.",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying (MoFAHD)",
        "department": "Department of Fisheries",
        "target_beneficiaries": "Rural women, SHG members, youth, and marginal fish farmers.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Ornamental Fish Breeders, Women SHG Members, Rural Youth",
        "business_type": "Agri-Allied, Manufacturing",
        "project_type": "Backyard glass aquarium and FRP tank units, indigenous ornamental fish breeding, aquatic plant propagation",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Unit cost of ₹3,00,000 for backyard ornamental unit.",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 300000.0,
        "financial_assistance": "Direct back-ended capital subsidy of 40% (General) or 60% (SC/ST/Women).",
        "subsidy_details": "40% subsidy (₹1.20 Lakh) for General; 60% subsidy (₹1.80 Lakh) for SC, ST, and Women beneficiaries.",
        "subsidy_percentage": 60.0,
        "max_subsidy_amount": 180000.0,
        "interest_rate": "Commercial bank lending rate on remaining amount.",
        "margin_money": "10% to 20% beneficiary contribution.",
        "repayment_period": "Up to 3 to 5 years",
        "moratorium": "3 months",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 300000.0,
        "benefits": "High 60% capital subsidy, requires small space (100-200 sq.ft.), high weekly income from aquarium retail shops, simple maintenance.",
        "required_documents": "Aadhaar Card, Land / Backyard possession proof, Bank Account details, Caste certificate (if SC/ST), Passport-size photo.",
        "application_mode": "Offline via District Fisheries Office or Online on PMMSY portal",
        "application_steps": "1. Approach local District Fisheries Office. 2. Submit application for Backyard Ornamental Fish Rearing. 3. Officer inspects water source and space. 4. Construction of tanks. 5. Subsidy released directly to bank account.",
        "official_application_portal": "https://pmmsy.dof.gov.in/",
        "application_portal_name": "PMMSY National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://pmmsy.dof.gov.in/",
        "tracking_instructions": "Check with District Fisheries Officer or enter Application ID on pmmsy.dof.gov.in.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Fisheries Offices, State Fisheries Federations",
        "official_helpline": "1800-425-1660",
        "official_email": "pmmsy-ornamental@dof.gov.in",
        "official_source_url": "https://pmmsy.dof.gov.in/",
        "official_guideline_url": "https://pmmsy.dof.gov.in/guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "RKVY-RAFTAAR-87",
        "official_scheme_name": "RKVY-RAFTAAR Agripreneurship Orientation Programme",
        "short_description": "Provides monthly stipends of ₹10,000 during 2 months of agribusiness incubation followed by seed-stage grants up to ₹5 Lakh to ₹25 Lakh for innovative farm startups.",
        "ministry": "Ministry of Agriculture and Farmers Welfare (MoA&FW)",
        "department": "RKVY Division",
        "target_beneficiaries": "Rural youth, agricultural graduates, innovators, and early-stage agri-business founders.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 45 years",
        "minimum_age": 18,
        "maximum_age": 45,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Agri-Entrepreneurs, Innovators, Farm Tech Developers, Rural Youth",
        "business_type": "Manufacturing, Service, Agri-Allied",
        "project_type": "Agtech solutions, precision farming, drone crop monitoring, organic inputs, waste valorisation, direct farm-to-fork logistics",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Grant-in-aid up to ₹5,00,000 (Idea stage) and up to ₹25,00,000 (Seed stage).",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 2500000.0,
        "financial_assistance": "100% grant-in-aid + ₹10,000/month stipend during incubation at Knowledge Partners (KPs) and R-ABIs.",
        "subsidy_details": "100% grant assistance (up to ₹5 Lakh for Agripreneurship Orientation, up to ₹25 Lakh for Seed Stage).",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 2500000.0,
        "interest_rate": "Nil (100% Government Grant)",
        "margin_money": "10% to 15% minimum contribution from seed-stage startups.",
        "repayment_period": "Not applicable (Grant)",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 2500000.0,
        "benefits": "Equity-free grant up to ₹25 Lakh, 2-month world-class incubation at ICAR/IARI institutes, monthly living stipend during training.",
        "required_documents": "Pitch Deck / Innovative Agri Proposal, Aadhaar Card, PAN Card, Certificate of Incorporation / DPIIT Recognition (if registered startup), Bank Account details.",
        "application_mode": "Online via designated Knowledge Partners (KPs) and R-ABIs (e.g., IARI, CCS HAU, MANAGE)",
        "application_steps": "1. Apply to nearest RKVY-RAFTAAR Agri-Business Incubator (R-ABI). 2. Present innovation in Pitching Round. 3. Complete 2-month incubation with ₹10,000/month stipend. 4. Independent Committee sanctions grant. 5. Grant disbursed in milestone tranches.",
        "official_application_portal": "https://rkvy.nic.in/",
        "application_portal_name": "RKVY-RAFTAAR National Portal",
        "application_tracking_available": True,
        "tracking_url": "https://rkvy.nic.in/",
        "tracking_instructions": "Log on to respective R-ABI incubator portal or check application registration number.",
        "channel_partner_requirement": True,
        "channel_partner_types": "ICAR Institutes, Agricultural Universities, IIMs, MANAGE Hyderabad, NIAM Jaipur",
        "official_helpline": "011-23381012",
        "official_email": "rkvy-raftaar@gov.in",
        "official_source_url": "https://rkvy.nic.in/",
        "official_guideline_url": "https://rkvy.nic.in/Agripreneurship.html",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "OPERATION-GREENS-88",
        "official_scheme_name": "Operation Greens - Long Term Integrated Value Chain",
        "short_description": "Provides 50% capital subsidy up to ₹15 Crore for setting up post-harvest processing, logistics, and integrated cold chains for Tomato, Onion, Potato (TOP) and notified crops.",
        "ministry": "Ministry of Food Processing Industries (MoFPI)",
        "department": "Operation Greens Division",
        "target_beneficiaries": "Farmer Producer Organizations (FPOs), processing firms, cooperatives, and supply-chain logistics entrepreneurs.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income limit specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "FPO Leaders, Food Processors, Cold Chain Operators, Agri Transporters",
        "business_type": "Manufacturing, Agri-Allied, Service",
        "project_type": "Integrated value chain development: farm-gate primary processing, sorting, grading, climate-controlled transport, retail kiosks",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Grant-in-aid up to ₹15.00 Crore per project.",
        "min_loan_amount": 10000000.0,
        "max_loan_amount": 150000000.0,
        "financial_assistance": "50% grant of eligible project cost (70% for FPOs) up to ₹15 Crore.",
        "subsidy_details": "50% capital subsidy for regular promoters; 70% capital subsidy for Farmer Producer Organizations.",
        "subsidy_percentage": 70.0,
        "max_subsidy_amount": 150000000.0,
        "interest_rate": "Commercial bank lending rate on debt component.",
        "margin_money": "Minimum 20% promoter contribution.",
        "repayment_period": "Up to 7 to 10 years",
        "moratorium": "Up to 2 years",
        "collateral_requirement": "Mortgage of integrated value chain infrastructure.",
        "project_cost_limit": 150000000.0,
        "benefits": "Very large subsidy up to ₹15 Crore, cuts farm gate price volatility, guarantees fair farm realization, prevents distress sales.",
        "required_documents": "Detailed Project Report (DPR), Bank appraisal and sanction letter, Land title / lease for minimum 15 years, FPO registration / MCA incorporation.",
        "application_mode": "Online on MoFPI Portal",
        "application_steps": "1. Review open EoI on mofpi.gov.in. 2. Submit integrated value chain proposal with DPR. 3. Mission Directorate appraises proposal. 4. IMAC sanctions grant. 5. Funds released across 4 construction and operational milestones.",
        "official_application_portal": "https://www.mofpi.gov.in/",
        "application_portal_name": "MoFPI SAMPADA Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.mofpi.gov.in/",
        "tracking_instructions": "Enter Proposal Registration ID on MoFPI SAMPADA portal.",
        "channel_partner_requirement": True,
        "channel_partner_types": "National Agricultural Cooperative Marketing Federation (NAFED), Scheduled Banks",
        "official_helpline": "011-26406500",
        "official_email": "operationgreens-mofpi@gov.in",
        "official_source_url": "https://www.mofpi.gov.in/",
        "official_guideline_url": "https://www.mofpi.gov.in/schemes/operation-greens",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "TN-NEEDS-89",
        "official_scheme_name": "New Entrepreneur-cum-Enterprise Development Scheme (NEEDS) - Tamil Nadu",
        "short_description": "Tamil Nadu Government flagship scheme providing 25% capital subsidy up to ₹75 Lakh and 3% interest subvention for first-generation educated entrepreneurs.",
        "ministry": "Government of Tamil Nadu",
        "department": "Micro, Small and Medium Enterprises (MSME) Department",
        "target_beneficiaries": "First-generation educated youth entrepreneurs setting up new manufacturing or service enterprises in Tamil Nadu.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "21 to 45 years (up to 45 for SC/ST/BC/MBC/Women/Differently Abled; up to 35 for General)",
        "minimum_age": 21,
        "maximum_age": 45,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Tamil Nadu",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Educated Youth, First-generation Entrepreneurs, Engineers, Diploma Holders, Graduates",
        "business_type": "Manufacturing, Service",
        "project_type": "New industrial units, automotive components, textile manufacturing, food processing, IT enabled services, solar engineering",
        "education_requirements": "Degree, Diploma, or ITI / Vocational Certificate from recognized institution.",
        "loan_amount": "Project cost between ₹10 Lakh and ₹5 Crore (TIIC or Commercial Banks).",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 50000000.0,
        "financial_assistance": "25% State Capital Subsidy (up to ₹75 Lakh) + 3% interest subvention for the entire loan repayment period.",
        "subsidy_details": "25% capital subsidy on plant and machinery (max ₹75 Lakh) + 3% interest subvention rebate + EDP training.",
        "subsidy_percentage": 25.0,
        "max_subsidy_amount": 7500000.0,
        "interest_rate": "Bank / TIIC lending rate minus 3% interest subvention.",
        "margin_money": "5% for Special Categories (SC/ST/BC/MBC/Women); 10% for General Category.",
        "repayment_period": "Up to 5 to 7 years",
        "moratorium": "Up to 1 year",
        "collateral_requirement": "Covered under CGTMSE credit guarantee up to ₹5 Crore.",
        "project_cost_limit": 50000000.0,
        "benefits": "State subsidy up to ₹75 Lakh, 3% interest rebate, only 5% promoter equity for women and reserved categories, free EDI entrepreneurship training.",
        "required_documents": "Degree / Diploma Certificate, Community Certificate (for SC/ST/BC/MBC), Aadhaar Card, Detailed Project Report (DPR), Machinery quotations, Land ownership or lease documents (minimum 5 years).",
        "application_mode": "Online on MSME Tamil Nadu Portal",
        "application_steps": "1. Visit msmeonline.tn.gov.in. 2. Register under NEEDS Scheme. 3. Upload educational proof and DPR. 4. District Level Task Force Committee (DLTFC) chaired by District Collector interviews applicant. 5. Sanction issued to TIIC or Commercial Bank. 6. Attend mandatory EDI training before disbursement.",
        "official_application_portal": "https://www.msmeonline.tn.gov.in/needs/",
        "application_portal_name": "Tamil Nadu MSME NEEDS Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.msmeonline.tn.gov.in/needs/",
        "tracking_instructions": "Enter Application Number and Date of Birth on msmeonline.tn.gov.in to check DLTFC interview schedule and sanction status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Industries Centres (DIC), Tamil Nadu Industrial Investment Corporation (TIIC), Public Sector Commercial Banks",
        "official_helpline": "044-22502444",
        "official_email": "indcom@nic.in",
        "official_source_url": "https://cms.tn.gov.in/sites/default/files/gos/msme_e_28_2021.pdf",
        "official_guideline_url": "https://www.msmeonline.tn.gov.in/needs/guidelines.php",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "TN-UYEGP-90",
        "official_scheme_name": "Unemployed Youth Employment Generation Programme (UYEGP) - Tamil Nadu",
        "short_description": "Provides 25% capital subsidy up to ₹1.25 Lakh for unemployed youth in Tamil Nadu to establish micro-enterprises in manufacturing, service, and business sectors.",
        "ministry": "Government of Tamil Nadu",
        "department": "Department of Industries and Commerce / District Industries Centres (DIC)",
        "target_beneficiaries": "Unemployed youth in Tamil Nadu with family annual income up to ₹5,00,000.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 45 years (up to 45 for SC/ST/BC/MBC/Women; up to 35 for General)",
        "minimum_age": 18,
        "maximum_age": 45,
        "income_limit": 500000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Tamil Nadu",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Unemployed Youth, Artisans, Electricians, Mechanics, Tailors, Retailers",
        "business_type": "Manufacturing, Service, Trading / Retail",
        "project_type": "Manufacturing (up to ₹15 Lakh), Service (up to ₹5 Lakh), Business/Trading (up to ₹5 Lakh)",
        "education_requirements": "Minimum 8th standard pass.",
        "loan_amount": "Up to ₹15 Lakh (Manufacturing) and up to ₹5 Lakh (Service / Business).",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 1500000.0,
        "financial_assistance": "25% government subsidy credited directly to bank account, 90% to 95% bank loan.",
        "subsidy_details": "25% capital subsidy of project cost (maximum ₹1,25,000 for manufacturing and services).",
        "subsidy_percentage": 25.0,
        "max_subsidy_amount": 125000.0,
        "interest_rate": "Commercial bank lending rate on MSME credit.",
        "margin_money": "5% for Special Categories (SC/ST/BC/MBC/Women); 10% for General Category.",
        "repayment_period": "Up to 5 years",
        "moratorium": "6 months",
        "collateral_requirement": "Nil (Covered under CGTMSE).",
        "project_cost_limit": 1500000.0,
        "benefits": "25% capital subsidy, 7 days free entrepreneurship training by EDI, low 5% promoter margin, zero collateral.",
        "required_documents": "8th Pass / Transfer Certificate, Community Certificate, Income Certificate (< ₹5 Lakh), Aadhaar Card, Project Quotation, Proof of Residence in TN.",
        "application_mode": "Online on MSME Tamil Nadu Portal",
        "application_steps": "1. Visit msmeonline.tn.gov.in/uyegp. 2. Fill online application and choose target bank branch. 3. Attend District Task Force Committee interview. 4. Complete 7-day EDP training. 5. Bank disburses loan and claims 25% subsidy.",
        "official_application_portal": "https://www.msmeonline.tn.gov.in/uyegp/",
        "application_portal_name": "Tamil Nadu UYEGP Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.msmeonline.tn.gov.in/uyegp/",
        "tracking_instructions": "Enter Application ID on msmeonline.tn.gov.in/uyegp to check committee scrutiny, bank selection, and subsidy release.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Industries Centres (DIC), Public Sector Commercial Banks, Regional Rural Banks (Pandyan / Pallavan / TNGB)",
        "official_helpline": "044-22502444",
        "official_email": "indcom@nic.in",
        "official_source_url": "https://www.msmeonline.tn.gov.in/uyegp/",
        "official_guideline_url": "https://www.msmeonline.tn.gov.in/uyegp/guidelines.php",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "TN-TAHDCO-FAST-91",
        "official_scheme_name": "TAHDCO Fast Track Subsidy Scheme - Tamil Nadu",
        "short_description": "Provides 30% to 50% capital subsidy (up to ₹2.25 Lakh) for Scheduled Caste (SC) and Scheduled Tribe (ST) entrepreneurs in Tamil Nadu to launch diverse businesses.",
        "ministry": "Government of Tamil Nadu",
        "department": "Tamil Nadu Adi Dravidar Housing and Development Corporation (TAHDCO)",
        "target_beneficiaries": "Scheduled Caste (SC) and Scheduled Tribe (ST) individuals living in Tamil Nadu.",
        "eligible_categories": "SC,ST",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": 300000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Tamil Nadu",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "SC/ST Youth, Small Shopkeepers, Transporters, Tailors, Artisans",
        "business_type": "Manufacturing, Service, Trading / Retail, Agri-Allied",
        "project_type": "Commercial passenger vehicles, light transport, modern tailoring, photocopy/printing centres, grocery trade, clinic setup",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹10,00,000 project cost with TAHDCO back-ended subsidy.",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 1000000.0,
        "financial_assistance": "30% capital subsidy for general economic activities; 50% for special priority segments credited directly to bank account.",
        "subsidy_details": "30% capital subsidy of project cost (max ₹2,25,000) for general trades; up to 50% subsidy for specialized empowerment programs.",
        "subsidy_percentage": 30.0,
        "max_subsidy_amount": 225000.0,
        "interest_rate": "Commercial bank lending rate on the loan portion.",
        "margin_money": "5% promoter contribution.",
        "repayment_period": "Up to 5 years",
        "moratorium": "3 to 6 months",
        "collateral_requirement": "Nil for loans up to ₹10 Lakh covered under CGTMSE / TAHDCO norms.",
        "project_cost_limit": 1000000.0,
        "benefits": "Generous 30% to 50% capital subsidy, fast-track processing through District TAHDCO Managers, high approval rates for marginalized youth.",
        "required_documents": "Permanent Community Certificate (SC/ST), Family Annual Income Certificate (< ₹3 Lakh), Aadhaar Card, Smart Ration Card, Driving License (if applying for vehicle), Quotation from authorized vendor.",
        "application_mode": "Online on TAHDCO Application Portal",
        "application_steps": "1. Visit tahdco.tn.gov.in. 2. Select 'Economic Development Schemes'. 3. Fill personal and business details. 4. Upload SC/ST certificate and quotation. 5. District TAHDCO Manager and Lead Bank Manager conduct interview. 6. Subsidy released directly to loan account.",
        "official_application_portal": "https://tahdco.tn.gov.in/",
        "application_portal_name": "TAHDCO Official Portal",
        "application_tracking_available": True,
        "tracking_url": "https://tahdco.tn.gov.in/",
        "tracking_instructions": "Enter Application Reference Number on tahdco.tn.gov.in to verify district committee approval and subsidy release status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District TAHDCO Offices, Public Sector Banks, Tamil Nadu Grama Bank",
        "official_helpline": "044-25846100",
        "official_email": "tahdco@tn.gov.in",
        "official_source_url": "https://tahdco.tn.gov.in/",
        "official_guideline_url": "https://tahdco.tn.gov.in/schemes",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "TN-TAHDCO-PETROL-92",
        "official_scheme_name": "TAHDCO Petrol/Diesel Retail Outlet Scheme - Tamil Nadu",
        "short_description": "Provides financial assistance and 30% capital subsidy up to ₹3,00,000 for SC/ST individuals allotted retail petroleum dealerships by Oil Marketing Companies (OMCs).",
        "ministry": "Government of Tamil Nadu",
        "department": "Tamil Nadu Adi Dravidar Housing and Development Corporation (TAHDCO)",
        "target_beneficiaries": "Scheduled Caste (SC) and Scheduled Tribe (ST) individuals selected as dealers by public sector oil marketing companies (IOCL, BPCL, HPCL).",
        "eligible_categories": "SC,ST",
        "gender_eligibility": "All",
        "age_eligibility": "21 to 60 years",
        "minimum_age": 21,
        "maximum_age": 60,
        "income_limit": None,
        "income_period": "No income ceiling for retail petroleum dealerships",
        "location_eligibility": "Tamil Nadu",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "SC/ST Petrol Pump Dealership Allottees",
        "business_type": "Trading / Retail, Service",
        "project_type": "Petrol/diesel retail bunk infrastructure, canopy, underground tanks, dispensing pumps, working capital for fuel stocks",
        "education_requirements": "Minimum 10th standard pass (as per OMC dealership norms).",
        "loan_amount": "Up to ₹10,00,000 financial assistance / loan with 30% capital subsidy.",
        "min_loan_amount": 200000.0,
        "max_loan_amount": 1000000.0,
        "financial_assistance": "30% capital subsidy (up to ₹3 Lakh) paired with commercial bank credit.",
        "subsidy_details": "30% capital subsidy (max ₹3,00,000) released directly to the bank account.",
        "subsidy_percentage": 30.0,
        "max_subsidy_amount": 300000.0,
        "interest_rate": "Commercial bank lending rate on the loan portion.",
        "margin_money": "10% promoter contribution.",
        "repayment_period": "Up to 5 to 7 years",
        "moratorium": "6 months",
        "collateral_requirement": "Hypothecation of dealership equipment and fuel stocks.",
        "project_cost_limit": 1000000.0,
        "benefits": "₹3 Lakh direct government subsidy, bridges working capital requirements for newly allotted SC/ST petroleum dealers, permanent high revenue stream.",
        "required_documents": "Letter of Intent (LoI) / Dealership Allotment Letter from IOCL/BPCL/HPCL, SC/ST Community Certificate, Aadhaar Card, PAN Card, Site Lease or Ownership deed.",
        "application_mode": "Online on TAHDCO Portal",
        "application_steps": "1. Receive Letter of Intent from OMC. 2. Apply on tahdco.tn.gov.in under Petroleum Dealership Scheme. 3. District TAHDCO Manager verifies LoI. 4. Subsidy sanctioned and released to financing bank.",
        "official_application_portal": "https://tahdco.tn.gov.in/",
        "application_portal_name": "TAHDCO Portal",
        "application_tracking_available": True,
        "tracking_url": "https://tahdco.tn.gov.in/",
        "tracking_instructions": "Track status at District TAHDCO Manager office.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Oil Marketing Companies (IOCL/BPCL/HPCL), District TAHDCO Offices, Commercial Banks",
        "official_helpline": "044-25846100",
        "official_email": "tahdco@tn.gov.in",
        "official_source_url": "https://tahdco.tn.gov.in/",
        "official_guideline_url": "https://tahdco.tn.gov.in/schemes",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "TN-AABCS-93",
        "official_scheme_name": "Tamil Nadu Annal Ambedkar Business Champions Scheme (AABCS)",
        "short_description": "Landmark scheme providing 35% capital subsidy up to ₹1.5 Crore and 6% interest subvention for Scheduled Caste and Scheduled Tribe entrepreneurs in Tamil Nadu.",
        "ministry": "Government of Tamil Nadu",
        "department": "Micro, Small and Medium Enterprises (MSME) Department",
        "target_beneficiaries": "Scheduled Caste (SC) and Scheduled Tribe (ST) entrepreneurs setting up manufacturing, service, or trading enterprises in Tamil Nadu.",
        "eligible_categories": "SC,ST",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 55 years",
        "minimum_age": 18,
        "maximum_age": 55,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Tamil Nadu",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "SC/ST Entrepreneurs, Engineers, Small Factory Owners, Transporters, Service Providers",
        "business_type": "Manufacturing, Service, Trading / Retail",
        "project_type": "Precision engineering, textile garment units, commercial fleet, medical diagnostics, software firms, agro processing",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Project cost up to ₹5 Crore (TIIC or Commercial Banks).",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 50000000.0,
        "financial_assistance": "35% capital subsidy (up to ₹1.5 Crore) + 6% interest subvention for up to 10 years.",
        "subsidy_details": "35% upfront capital subsidy on plant, machinery, and equipment (max ₹1.50 Crore) + 6% interest subvention.",
        "subsidy_percentage": 35.0,
        "max_subsidy_amount": 15000000.0,
        "interest_rate": "Bank lending rate minus 6% interest subvention (effective ~3% - 4.5% p.a.).",
        "margin_money": "Only 5% promoter contribution required.",
        "repayment_period": "Up to 7 to 10 years",
        "moratorium": "Up to 1 year",
        "collateral_requirement": "Covered under CGTMSE credit guarantee.",
        "project_cost_limit": 50000000.0,
        "benefits": "Highest state capital subsidy (up to ₹1.5 Crore), 6% interest subvention, lowest promoter margin (5%), comprehensive technical handholding.",
        "required_documents": "SC/ST Community Certificate, Aadhaar Card, PAN Card, Detailed Project Report, Machinery quotations, Factory land lease or purchase documents.",
        "application_mode": "Online on Tamil Nadu MSME Portal",
        "application_steps": "1. Visit msmeonline.tn.gov.in/aabcs. 2. Fill online application and submit DPR. 3. District Industries Centre (DIC) inspects proposal. 4. District Level Committee chaired by District Collector approves project. 5. Subsidy released directly to bank account.",
        "official_application_portal": "https://www.msmeonline.tn.gov.in/aabcs/",
        "application_portal_name": "Tamil Nadu AABCS Portal",
        "application_tracking_available": True,
        "tracking_url": "https://www.msmeonline.tn.gov.in/aabcs/",
        "tracking_instructions": "Enter Application ID on msmeonline.tn.gov.in/aabcs to check Committee approval, bank sanction, and subsidy release status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Industries Centres (DIC), Tamil Nadu Industrial Investment Corporation (TIIC), Commercial Banks",
        "official_helpline": "044-22502444",
        "official_email": "aabcs.msme@tn.gov.in",
        "official_source_url": "https://www.msmeonline.tn.gov.in/aabcs/",
        "official_guideline_url": "https://cms.tn.gov.in/sites/default/files/gos/msme_e_28_2023.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "UP-MMYSY-94",
        "official_scheme_name": "Mukhyamantri Yuva Swarojgar Yojana (MMYSY) - Uttar Pradesh",
        "short_description": "Provides loans up to ₹25 Lakh for manufacturing and ₹5 Lakh for service sector with 25% margin money subsidy to unemployed educated youth in Uttar Pradesh.",
        "ministry": "Government of Uttar Pradesh",
        "department": "Department of Micro, Small and Medium Enterprises and Export Promotion",
        "target_beneficiaries": "Educated unemployed youth who are residents of Uttar Pradesh.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 40 years",
        "minimum_age": 18,
        "maximum_age": 40,
        "income_limit": None,
        "income_period": "No family income ceiling specified in official guidelines",
        "location_eligibility": "Uttar Pradesh",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Unemployed Youth, Technical Graduates, Artisans, Small Businessmen",
        "business_type": "Manufacturing, Service",
        "project_type": "Manufacturing units (up to ₹25 Lakh) and Service/Retail units (up to ₹5 Lakh)",
        "education_requirements": "Minimum 10th standard (High School) pass from recognized board.",
        "loan_amount": "Up to ₹25,00,000 (Manufacturing) and up to ₹5,00,000 (Service sector).",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 2500000.0,
        "financial_assistance": "25% margin money capital subsidy provided by UP Government (converted to grant after 2 years successful operation).",
        "subsidy_details": "25% margin money subsidy (maximum ₹6.25 Lakh for Industry; maximum ₹1.25 Lakh for Service).",
        "subsidy_percentage": 25.0,
        "max_subsidy_amount": 625000.0,
        "interest_rate": "Commercial bank lending rate on MSME credit.",
        "margin_money": "10% for General; 5% for SC/ST/OBC/Women/Minority.",
        "repayment_period": "Up to 5 to 7 years",
        "moratorium": "6 months",
        "collateral_requirement": "Covered under CGTMSE credit guarantee.",
        "project_cost_limit": 2500000.0,
        "benefits": "25% capital subsidy, fast-track online approval via DIUP portal, only 5% promoter equity for reserved categories and women.",
        "required_documents": "10th Marksheet / Passing Certificate, UP Domicile Certificate, Aadhaar Card, PAN Card, Detailed Project Report, Bank Passbook, Caste Certificate (if applicable).",
        "application_mode": "Online on UP DIUP Portal",
        "application_steps": "1. Visit diupmsme.upsdc.gov.in. 2. Register under Mukhyamantri Yuva Swarojgar Yojana. 3. Fill applicant details and upload DPR. 4. District Task Force Committee headed by District Magistrate interviews candidate. 5. Sanctioned and disbursed by bank.",
        "official_application_portal": "https://diupmsme.upsdc.gov.in/",
        "application_portal_name": "UP MSME Online Portal (DIUP)",
        "application_tracking_available": True,
        "tracking_url": "https://diupmsme.upsdc.gov.in/",
        "tracking_instructions": "Enter Application ID on diupmsme.upsdc.gov.in to check Task Force Committee status and bank forwarding.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Industries Centres (DIC), State Bank of India, Baroda UP Bank, PNB, Aryavart Bank",
        "official_helpline": "1800-1800-888",
        "official_email": "diupmsme@gmail.com",
        "official_source_url": "https://diupmsme.upsdc.gov.in/",
        "official_guideline_url": "https://diupmsme.upsdc.gov.in/doc/MMYSY_Guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "MH-CMEGP-95",
        "official_scheme_name": "Chief Minister's Employment Generation Programme (CMEGP) - Maharashtra",
        "short_description": "Maharashtra Government scheme offering 15% to 35% capital subsidy up to ₹10 Lakh for rural and urban youth to start manufacturing and service micro-enterprises.",
        "ministry": "Government of Maharashtra",
        "department": "Directorate of Industries",
        "target_beneficiaries": "Educated unemployed youth and micro-entrepreneurs residing in Maharashtra.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 45 years (up to 50 for SC/ST/Women/Differently Abled; up to 45 for General)",
        "minimum_age": 18,
        "maximum_age": 50,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Maharashtra",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Unemployed Youth, Technicians, Artisans, Small Businessmen",
        "business_type": "Manufacturing, Service",
        "project_type": "Manufacturing projects (up to ₹50 Lakh) and Service/Agri-allied projects (up to ₹10 Lakh)",
        "education_requirements": "Minimum 7th standard pass (for projects > ₹10 Lakh in manufacturing; 10th pass for > ₹25 Lakh).",
        "loan_amount": "Up to ₹50,00,000 for Manufacturing; Up to ₹10,00,000 for Service sector.",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 5000000.0,
        "financial_assistance": "Direct back-ended capital subsidy credited to bank account; bank credit of 85% to 95% of project cost.",
        "subsidy_details": "Special categories (SC/ST/Women/Minority/Rural): 35% in Rural, 25% in Urban. General category: 25% in Rural, 15% in Urban.",
        "subsidy_percentage": 35.0,
        "max_subsidy_amount": 1000000.0,
        "interest_rate": "Commercial bank lending rate on MSME credit.",
        "margin_money": "5% for Special Categories (SC/ST/Women/OBC/Rural); 10% for General Urban.",
        "repayment_period": "Up to 5 to 7 years",
        "moratorium": "6 months",
        "collateral_requirement": "Covered under CGTMSE credit guarantee.",
        "project_cost_limit": 5000000.0,
        "benefits": "High 35% capital subsidy, low 5% promoter margin, online portal with bank integration, free EDI skill training.",
        "required_documents": "Aadhaar Card, Maharashtra Domicile Certificate, 7th/10th Marksheet, Caste Certificate (if applicable), Detailed Project Report, Bank Passbook.",
        "application_mode": "Online on Maharashtra MahaCMEGP Portal",
        "application_steps": "1. Visit maha-cmegp.gov.in. 2. Register with Aadhaar number. 3. Fill project details and upload DPR. 4. District Level Task Force Committee (DLTFC) evaluates application. 5. Direct forwarding to financing bank.",
        "official_application_portal": "https://maha-cmegp.gov.in/",
        "application_portal_name": "Maharashtra CMEGP Portal",
        "application_tracking_available": True,
        "tracking_url": "https://maha-cmegp.gov.in/",
        "tracking_instructions": "Enter Application ID on maha-cmegp.gov.in to check DLTFC clearance and bank sanction status.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Industries Centres (DIC), Maharashtra State Financial Corporation (MSFC), Commercial Banks, RRBs",
        "official_helpline": "022-22023584",
        "official_email": "cmegp.support@maharashtra.gov.in",
        "official_source_url": "https://maha-cmegp.gov.in/",
        "official_guideline_url": "https://maha-cmegp.gov.in/homepage/scheme-guidelines",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "STATE-RGUMY-96",
        "official_scheme_name": "Rajiv Gandhi Udyami Mitra Yojana (RGUMY) - Handholding Scheme",
        "short_description": "Provides dedicated institutional handholding support and advisory stipends to first-generation micro-entrepreneurs through certified Udyami Mitras.",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "department": "National Institute for Micro, Small and Medium Enterprises (NI-MSME)",
        "target_beneficiaries": "First-generation micro-entrepreneurs, rural youth, women, and marginalized artisans setting up new enterprises.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Pan-India",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "New Entrepreneurs, Rural Micro-Business Owners, Technical Apprentices",
        "business_type": "Manufacturing, Service, Trading / Retail",
        "project_type": "Handholding assistance for micro-enterprise setup: DPR preparation, loan documentation, statutory licenses, marketing setup",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Financial assistance / handholding grant of ₹4,000 to ₹6,000 per assisted enterprise.",
        "min_loan_amount": 4000.0,
        "max_loan_amount": 6000.0,
        "financial_assistance": "100% government funded handholding grant paid to certified business mentor to assist the entrepreneur at zero cost to the citizen.",
        "subsidy_details": "100% free handholding services funded by Ministry of MSME.",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 6000.0,
        "interest_rate": "Nil (Government Service Grant)",
        "margin_money": "Nil.",
        "repayment_period": "Not applicable",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 2500000.0,
        "benefits": "Zero-cost business mentorship, expert help with bank DPRs and approvals, prevents enterprise failure in early stages.",
        "required_documents": "Aadhaar Card, Udyam Registration, Proposed Business Outline.",
        "application_mode": "Offline via District Industries Centres / MSME Development Institutes",
        "application_steps": "1. Approach local MSME Development and Facilitation Office (MSME-DFO). 2. Request assignment of certified Udyami Mitra. 3. Mentor guides through project report, licensing, and bank loan sanction.",
        "official_application_portal": "https://msme.gov.in/",
        "application_portal_name": "Ministry of MSME Portal",
        "application_tracking_available": True,
        "tracking_url": "https://msme.gov.in/",
        "tracking_instructions": "Inquire with MSME-DFO Assistant Director.",
        "channel_partner_requirement": True,
        "channel_partner_types": "MSME Development Institutes, District Industries Centres, NI-MSME Hyderabad",
        "official_helpline": "011-23063288",
        "official_email": "nimsme@nic.in",
        "official_source_url": "https://msme.gov.in/",
        "official_guideline_url": "https://msme.gov.in/sites/default/files/RGUMY_Guidelines.pdf",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "ASSAM-MMUA-97",
        "official_scheme_name": "Mukhyamantri Mahila Udyamita Abhiyan (MMUA) - Assam",
        "short_description": "Provides seed capital grants up to ₹35,000 in tranches for rural women SHG members in Assam to transition into individual micro-entrepreneurs.",
        "ministry": "Government of Assam",
        "department": "Assam State Rural Livelihoods Mission (ASRLM)",
        "target_beneficiaries": "Rural women Self Help Group members in Assam who prepare an individual business viability plan.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 55 years",
        "minimum_age": 18,
        "maximum_age": 55,
        "income_limit": 200000.0,
        "income_period": "Per Annum",
        "location_eligibility": "Assam",
        "rural_urban_eligibility": "Rural",
        "occupation_eligibility": "Rural Women, SHG Members, Weavers, Dairy Rearers, Artisans",
        "business_type": "Manufacturing, Service, Trading / Retail, Agri-Allied",
        "project_type": "Poultry farming, eri/muga silk weaving, tea nursery, small retail store, tailoring, pickle production",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹35,000 (₹10,000 direct grant in Year 1 + ₹25,000 bank loan / grant in Year 2).",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 35000.0,
        "financial_assistance": "Direct Benefit Transfer (DBT) grant of ₹10,000 upfront seed capital, followed by ₹12,500 government grant + ₹12,500 bank credit upon enterprise validation.",
        "subsidy_details": "Total direct grant component of ₹22,500 per rural woman entrepreneur.",
        "subsidy_percentage": 65.0,
        "max_subsidy_amount": 22500.0,
        "interest_rate": "0% on grant portion; concessional SHG rate on loan portion.",
        "margin_money": "Nil.",
        "repayment_period": "18 to 24 months for loan tranche.",
        "moratorium": "3 months",
        "collateral_requirement": "Nil.",
        "project_cost_limit": 35000.0,
        "benefits": "₹10,000 instant direct grant, no bank collateral, dedicated rural livelihood handholding by Gaon Panchayat.",
        "required_documents": "Aadhaar Card, SHG Passbook, Assam Domicile / Ration Card, Individual Business Plan, Child limitation self-declaration (as per state norms).",
        "application_mode": "Offline via Gaon Panchayat / Block Mission Management Unit (BMMU)",
        "application_steps": "1. Collect MMUA application form at Gaon Panchayat. 2. Submit individual business plan for selected livelihood. 3. Village Organization scrutinizes proposal. 4. First ₹10,000 grant credited directly to bank account via DBT.",
        "official_application_portal": "https://asrlms.assam.gov.in/",
        "application_portal_name": "Assam State Rural Livelihoods Mission Portal",
        "application_tracking_available": True,
        "tracking_url": "https://asrlms.assam.gov.in/",
        "tracking_instructions": "Check with Gaon Panchayat Coordinator or Block Project Manager, ASRLMS.",
        "channel_partner_requirement": True,
        "channel_partner_types": "Gaon Panchayats, Assam State Rural Livelihoods Mission, Assam Gramin Vikash Bank",
        "official_helpline": "1800-345-3525",
        "official_email": "asrlms.assam@gov.in",
        "official_source_url": "https://asrlms.assam.gov.in/",
        "official_guideline_url": "https://asrlms.assam.gov.in/schemes/mukhyamantri-mahila-udyamita-abhiyan",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "WB-BANGLASHREE-98",
        "official_scheme_name": "Banglashree Scheme for MSMEs - West Bengal",
        "short_description": "Offers fiscal incentives including up to ₹1 Crore capital subsidy, 20% electricity duty waiver, and stamp duty exemption for micro and small enterprises in West Bengal.",
        "ministry": "Government of West Bengal",
        "department": "Micro, Small & Medium Enterprises and Textiles Department",
        "target_beneficiaries": "Micro, small, and medium enterprises established in West Bengal.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "West Bengal",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "MSME Entrepreneurs, Factory Owners, Food Processors, Jute Manufacturers",
        "business_type": "Manufacturing, Service",
        "project_type": "Jute diversification, leather crafts, agro-processing, hosiery and garments, metal fabrication",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Fiscal incentives and subsidies on projects up to ₹10 Crore.",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 10000000.0,
        "financial_assistance": "Direct state capital subsidy up to ₹1 Crore depending on industrial zone classification (Zone A to Zone E).",
        "subsidy_details": "State capital investment subsidy up to 25% (max ₹1 Crore) + 100% electricity duty waiver for 5 years + 100% stamp duty refund.",
        "subsidy_percentage": 25.0,
        "max_subsidy_amount": 10000000.0,
        "interest_rate": "Commercial bank lending rate on loan component.",
        "margin_money": "15% to 20% promoter contribution.",
        "repayment_period": "Up to 7 years",
        "moratorium": "6 to 12 months",
        "collateral_requirement": "Covered under CGTMSE or standard bank charge.",
        "project_cost_limit": 50000000.0,
        "benefits": "Up to ₹1 Crore capital subsidy, 5 years zero electricity duty, full stamp duty reimbursement, fast single-window clearance through Shilpa Sathi.",
        "required_documents": "Udyam Registration Certificate, Land deeds / industrial estate allotment, Bank sanction letter, DPR, Pollution Control clearance.",
        "application_mode": "Online on West Bengal Shilpa Sathi Portal",
        "application_steps": "1. Visit shilpasathi.wb.gov.in. 2. Apply under Banglashree Scheme. 3. General Manager, District Industries Centre (DIC) inspects manufacturing site. 4. State Level Empowered Committee approves claim. 5. Subsidy released to bank account.",
        "official_application_portal": "https://shilpasathi.wb.gov.in/",
        "application_portal_name": "West Bengal Shilpa Sathi Portal",
        "application_tracking_available": True,
        "tracking_url": "https://shilpasathi.wb.gov.in/",
        "tracking_instructions": "Enter CAF (Common Application Form) Number on shilpasathi.wb.gov.in to check appraisal and subsidy release.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Industries Centres (DIC), West Bengal Small Industries Development Corporation (WBSIDC)",
        "official_helpline": "033-22145555",
        "official_email": "msmet.wb@gmail.com",
        "official_source_url": "https://wbmsme.gov.in/",
        "official_guideline_url": "https://wbmsme.gov.in/banglashree-scheme",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "ODISHA-MSHAKTI-99",
        "official_scheme_name": "Mission Shakti - 0% Interest SHG Loan Scheme (Odisha)",
        "short_description": "Odisha Government flagship scheme offering 0% interest loans up to ₹5,00,000 with 100% interest subvention for women self-help groups to scale micro-businesses.",
        "ministry": "Government of Odisha",
        "department": "Department of Mission Shakti",
        "target_beneficiaries": "Women Self Help Groups (WSHGs) in Odisha who take institutional credit for income generation.",
        "eligible_categories": "SC,ST,OBC,Minority,General,EWS",
        "gender_eligibility": "Female Only",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "No income ceiling specified in official guidelines",
        "location_eligibility": "Odisha",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Women SHG Members, Micro Entrepreneurs, Artisans, Fish Farmers",
        "business_type": "Manufacturing, Service, Trading / Retail, Agri-Allied",
        "project_type": "Mushroom cultivation, pisciculture in gram panchayat tanks, millet processing, school uniform stitching, electricity meter reading",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "Up to ₹5,00,000 at 0% effective interest rate.",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 500000.0,
        "financial_assistance": "100% interest subvention on commercial bank loans up to ₹5 Lakh, making loans completely interest-free (0% interest).",
        "subsidy_details": "100% interest subvention: bank interest is fully refunded to SHG savings account every quarter.",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 40000.0,
        "interest_rate": "0% (Zero Interest Loan)",
        "margin_money": "Nil.",
        "repayment_period": "Up to 3 to 5 years",
        "moratorium": "1 month",
        "collateral_requirement": "Nil (Mutual group guarantee).",
        "project_cost_limit": 500000.0,
        "benefits": "Complete 0% interest rate, guaranteed government procurement contracts (paddy procurement, mid-day meals, uniform stitching), rapid bank sanction.",
        "required_documents": "SHG Resolution and bank passbook, Aadhaar cards of members, Micro Credit Plan (MCP).",
        "application_mode": "Offline at any Commercial Bank / Odisha Gramya Bank or through Mission Shakti Coordinator",
        "application_steps": "1. WSHG passes resolution for income generation activity. 2. Submit loan proposal to nearest bank branch. 3. Bank sanctions loan up to ₹5 Lakh. 4. SHG repays regular installments; Mission Shakti automatically credits 100% interest back into SHG account quarterly.",
        "official_application_portal": "https://missionshakti.odisha.gov.in/",
        "application_portal_name": "Mission Shakti Odisha Portal",
        "application_tracking_available": True,
        "tracking_url": "https://missionshakti.odisha.gov.in/",
        "tracking_instructions": "Check interest subvention credit on the Mission Shakti MIS portal using SHG code.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Mission Shakti Units, Odisha Gramya Bank, State Bank of India, UCO Bank",
        "official_helpline": "0674-2391200",
        "official_email": "missionshakti.od@gov.in",
        "official_source_url": "https://missionshakti.odisha.gov.in/",
        "official_guideline_url": "https://missionshakti.odisha.gov.in/schemes/interest-subvention",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    },
    {
        "scheme_id": "TS-DALIT-BANDHU-100",
        "official_scheme_name": "Telangana Dalit Bandhu Scheme",
        "short_description": "Pioneering Telangana empowerment scheme providing a 100% direct grant of ₹10,00,000 with zero repayment and zero bank loan to eligible Dalit families for enterprise setup.",
        "ministry": "Government of Telangana",
        "department": "Scheduled Castes Development Department",
        "target_beneficiaries": "Scheduled Caste (Dalit) families residing in Telangana.",
        "eligible_categories": "SC",
        "gender_eligibility": "All",
        "age_eligibility": "18 to 65 years",
        "minimum_age": 18,
        "maximum_age": 65,
        "income_limit": None,
        "income_period": "Universal for eligible Dalit families in notified implementation phases",
        "location_eligibility": "Telangana",
        "rural_urban_eligibility": "Both",
        "occupation_eligibility": "Dalit Family Heads, Youth, Artisans, Agricultural Workers, Unemployed",
        "business_type": "Manufacturing, Service, Trading / Retail, Agri-Allied",
        "project_type": "Commercial transport (taxis, tractors, earthmovers), modern retail stores, dairy farming, medical labs, manufacturing workshops, hotels",
        "education_requirements": "None specified in the official source.",
        "loan_amount": "100% Grant of ₹10,00,000 per family.",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 1000000.0,
        "financial_assistance": "Direct Benefit Transfer (DBT) grant of ₹10 Lakh credited into special Dalit Bandhu bank account with no debt component.",
        "subsidy_details": "100% capital grant of ₹10,00,000 (No bank loan, zero repayment, completely debt-free).",
        "subsidy_percentage": 100.0,
        "max_subsidy_amount": 1000000.0,
        "interest_rate": "0% (100% Direct Grant)",
        "margin_money": "Nil (Zero promoter contribution).",
        "repayment_period": "Not applicable (100% Grant)",
        "moratorium": "Not applicable",
        "collateral_requirement": "Nil (Zero collateral).",
        "project_cost_limit": 1000000.0,
        "benefits": "Largest direct grant scheme in India (₹10 Lakh free grant), complete beneficiary freedom to choose any viable business, dedicated Dalit Security Fund for safety net.",
        "required_documents": "SC Caste Certificate, Food Security Card (Ration Card), Aadhaar Card, Passport Photograph, Special Dalit Bandhu Bank Account details.",
        "application_mode": "Offline via District Collector / District Scheduled Castes Development Officer (DSCDO)",
        "application_steps": "1. Family selected under Dalit Bandhu village/ward survey. 2. Choose preferred enterprise sector with guidance from resource person. 3. Special Dalit Bandhu bank account opened. 4. ₹10 Lakh grant transferred directly to bank account. 5. Assets procured and business commences.",
        "official_application_portal": "https://dalitbandhu.telangana.gov.in/",
        "application_portal_name": "Telangana Dalit Bandhu Portal",
        "application_tracking_available": True,
        "tracking_url": "https://dalitbandhu.telangana.gov.in/",
        "tracking_instructions": "Enter Ration Card or Aadhaar number on dalitbandhu.telangana.gov.in to verify survey registration and grant credit.",
        "channel_partner_requirement": True,
        "channel_partner_types": "District Collectors, Scheduled Castes Development Department, Telangana State SC Cooperative Development Corporation (TSSCCDC)",
        "official_helpline": "040-23391234",
        "official_email": "dalitbandhu@telangana.gov.in",
        "official_source_url": "https://dalitbandhu.telangana.gov.in/",
        "official_guideline_url": "https://scdevelopment.telangana.gov.in/",
        "last_verified_date": "2026-03-01",
        "verification_status": "Verified"
    }
]
